usememos/memos

utils/common.go
=> fix: local timezone

web/src/components/PreferencesSection.tsx, web/src/less/my-account-section.less, web/src/less/preferences-section.less, web/src/less/setting.less
fix text align in setting dialog #1
=> chore: polish setting dialog

api/memo.go, store/memo.go, web/src/components/AboutSiteDialog.tsx, web/src/components/ChangePasswordDialog.tsx, web/src/components/MyAccountSection.tsx, web/src/components/PreferencesSection.tsx, web/src/helpers/api.ts, web/src/less/change-password-dialog.less, web/src/less/menu-btns-popup.less, web/src/less/my-account-section.less, web/src/less/setting-dialog.less, web/src/services/memoService.ts
In the previous memos, we provided an "Export data as JSON". Use the exported `.json` file, so that we can import the data into newest memos.
Related issue: https://github.com/justmemos/memos/issues/46, https://github.com/justmemos/memos/issues/36
=> feat: import data with json file

server/resource.go, server/webhook.go, web/src/services/resourceService.ts
Update webhooks API `POST /h/:openId/resource` to upload resource with openId.
```bash
curl --request POST \
--url http://localhost:3000/h/:openId/resource \
--header 'content-type: multipart/form-data' \
--form file=@file
```
=> feat: upload resource by openid api

store/seed/10001__user.sql, store/sqlite.go, web/src/less/signin.less, web/src/pages/Signin.tsx
=> feat: seed data only in dev mode

api/memo.go, server/memo.go, server/webhook.go, store/memo.go
=> chore: find memo by tag

LICENSE, web/package.json, web/src/components/MemoCardDialog.tsx, web/src/components/MemoEditor.tsx, web/src/components/MemosHeader.tsx, web/src/components/SettingDialog.tsx, web/src/components/Sidebar.tsx, web/src/helpers/api.ts, web/src/less/app.less, web/src/less/global.less, web/src/less/home.less, web/src/less/memo-card-dialog.less, web/src/less/memo-trash-dialog.less, web/src/less/memos-header.less, web/src/less/menu-btns-popup.less, web/src/less/mixin.less, web/src/less/search-bar.less, web/src/less/setting-dialog.less, web/src/less/settings/my-account-section.less, web/src/less/siderbar.less, web/src/less/signin.less, web/src/pages/Home.tsx, web/tsconfig.json
https://user-images.githubusercontent.com/24653555/174463538-098daac4-5fb0-4c0f-9f0e-e2cfcfe49f38.mp4
=> feat: responsive view

web/src/components/DailyMemo.tsx, web/src/components/DeletedMemo.tsx, web/src/components/Memo.tsx, web/src/components/MemoCardDialog.tsx, web/src/components/MemoEditor.tsx, web/src/components/ShareMemoImageDialog.tsx, web/src/helpers/consts.ts, web/src/less/daily-memo-diary-dialog.less, web/src/less/memo-content.less, web/src/less/memo.less
Use markdown image syntax: `![]()`
=> chore: use markdown image syntax

web/src/components/Memo.tsx, web/src/components/MemoTrashDialog.tsx, web/src/less/memo.less
=> chore: expand/fold memo content button

web/src/less/memo-content.less
=> fix: content link style

server/webhook.go
Get tags by openid: `GET /h/:openId/tag`
=> chore: get tags by openid

docker-compose.yaml
docker-compose 启动方式，适配0.1.x后的版本。
=> chore: add docker-compose.yaml

web/src/components/MemoEditor.tsx
=> fix: Fix Typo (Editting -> Editing)

README.md, docker-compose.yml
ready to merge docker-compose.yml + readme update with docker-compose
=> Simple docker-compose.yml

web/src/components/UsageHeatMap.tsx, web/src/less/usage-heat-map.less
fix #194 
https://user-images.githubusercontent.com/17293034/188316910-63cc31dd-783e-43ac-a19a-1164225e29f2.mov
=> fix: heatmap popover blink

web/src/components/ResourcesDialog.tsx
fix #200 
看起来 422e190c9617ffb680a5445c75d415077bb20a48 加上的
=> fix: upload resouces double time

web/src/components/ArchivedMemo.tsx, web/src/components/ChangeMemoCreatedTsDialog.tsx, web/src/components/ChangePasswordDialog.tsx, web/src/components/CreateShortcutDialog.tsx, web/src/components/Memo.tsx, web/src/components/MemoCardDialog.tsx, web/src/components/MemoEditor.tsx, web/src/components/MemoList.tsx, web/src/components/Settings/MemberSection.tsx, web/src/components/Settings/MyAccountSection.tsx, web/src/components/ShareMemoImageDialog.tsx, web/src/locales/en.json, web/src/locales/zh.json, web/src/pages/Auth.tsx, web/src/pages/Home.tsx
=> update: i18n

web/src/components/MemoCardDialog.tsx, web/src/locales/en.json, web/src/locales/vi.json, web/src/locales/zh.json
I have a question: There any way we can add multilanguage for const `VISIBILITY_SELECTOR_ITEMS`?
=> chore: fix i18n vietnamese typos and update MemoCardDialog

api/user_setting.go, web/src/components/MemoEditor.tsx, web/src/components/Settings/PreferencesSection.tsx, web/src/less/memo-editor.less, web/src/locales/en.json, web/src/locales/vi.json, web/src/locales/zh.json, web/src/services/userService.ts, web/src/types/modules/setting.d.ts
=> feat: float mobile editor

web/src/pages/Auth.tsx
HTML5 form support to: 
- Validate email input
- Validate required input
- Enter to submit form (login or signup as host)
=> chore: support html form

web/src/components/Memo.tsx, web/src/components/MemoCardDialog.tsx, web/src/less/memo-detail.less, web/src/locales/en.json, web/src/locales/vi.json, web/src/locales/zh.json, web/src/pages/MemoDetail.tsx
=> feat: copy content

web/src/components/MemoFilter.tsx, web/src/components/SearchBar.tsx, web/src/locales/vi.json
=> fix: filter i18n

web/src/components/MemosHeader.tsx, web/src/components/ShortcutList.tsx, web/src/components/Sidebar.tsx, web/src/components/TagList.tsx, web/src/helpers/utils.ts, web/src/less/shortcut-list.less, web/src/less/siderbar.less, web/tailwind.config.js
* use standard `duration-300` instead of `duration-377`;
* use location listener to detect tag/shortcut item click;
* update css styles;
=> feat: update sidebar mask styles

web/src/labs/marked/marked.test.ts, web/src/labs/marked/parser/Table.ts, web/src/labs/marked/parser/index.ts, web/src/less/memo-content.less
=> feat: support markdown table

README.md
docker compose can't automatically upgrade according to latest tag
=> docs: docker compose tip

web/src/less/siderbar.less
https://user-images.githubusercontent.com/24653555/196065178-b0503003-7e85-4122-8033-f5bff97b9c99.mp4
=> chore: update mask animation styles

api/memo.go, server/memo.go, web/src/components/MemoEditor.tsx, web/src/types/modules/memo.d.ts
=> fix: patch memo with resource list

go.mod, go.sum, server/rss.go, server/server.go, web/vite.config.ts
=> feat: rss support

web/src/components/Memo.tsx, web/src/less/memo.less
=> feat: unpin button in the corner

web/src/components/Dialog/CommonDialog.tsx, web/src/less/common-dialog.less
I found that the current implementation of the  `CommonDialog` cannot display multi-line strings well (cannot parse '\n')
=> feat: dialog content enhancement

server/memo.go
Fix https://github.com/usememos/memos/pull/384
=> fix: memo list default value

web/src/labs/marked/parser/Blockquote.ts
```
面向具体实现编程 ==> 面向抽象接口编程
```
面向具体实现编程 ==
> 面向抽象接口编程
=> fix: abnormal blockquote regexp

web/src/components/CreateShortcutDialog.tsx, web/src/helpers/filter.ts, web/src/locales/en.json, web/src/locales/zh.json
=> feat: text filter regex support

web/src/components/UpdateVersionBanner.tsx, web/src/helpers/storage.ts, web/src/pages/Home.tsx
=> chore: allow skip version

web/src/components/ResourcesDialog.tsx, web/src/less/resources-dialog.less
=> chore: add icon

web/src/services/locationService.ts
=> fix: route confusion entering from non-home page

web/src/components/CreateShortcutDialog.tsx, web/src/helpers/filter.ts, web/src/less/create-shortcut-dialog.less, web/src/locales/en.json, web/src/locales/vi.json, web/src/locales/zh.json, web/src/types/filter.d.ts
[mp4格式视频](https://streamja.com/nz1Ee)
=> feat: add support for time-shortcut

web/src/components/Editor/Editor.tsx, web/src/components/MemoEditor.tsx, web/src/less/editor.less, web/src/less/explore.less, web/src/less/memo-editor.less
=> feat: update visibility selector style

api/user_setting.go, web/src/components/MemoEditor.tsx, web/src/components/Settings/PreferencesSection.tsx, web/src/less/memo-editor.less, web/src/services/userService.ts, web/src/types/modules/setting.d.ts
As we have additional style system setting, the mobile editor style user setting is not really needed anymore.
=> chore: remove mobile editor style user setting

web/src/components/MemoEditor.tsx, web/src/less/memo-editor.less, web/src/locales/en.json, web/src/locales/vi.json, web/src/locales/zh.json
=> chore: update cancel edit button style

web/src/pages/Auth.tsx
The previous limit was too short
* Closes #522
* Closes #519
=> feat: extend validation config max length

web/src/less/daily-review-dialog.less
=> fix: icon style

.github/workflows/build-and-push-test-image.yml
=> chore(revert): update test image platforms

web/src/less/explore.less, web/src/pages/Explore.tsx
=> feat: dark mode support for explore page

web/src/components/UsageHeatMap.tsx, web/src/less/usage-heat-map.less
Before
https://user-images.githubusercontent.com/118022040/204110668-8bed41bd-7d3a-4708-9b2b-5212f4b40f02.mov
After
https://user-images.githubusercontent.com/118022040/204110667-68e92be8-0c40-42af-b276-f6d5fe11dbc5.mov
=> fix: tooltip overlaps a window border

web/src/components/Settings/MemberSection.tsx
fixes #603 
simple, yet effective.
=> fix: password field visible

web/src/components/ChangeMemberPasswordDialog.tsx, web/src/components/Settings/MemberSection.tsx, web/src/less/common-dialog.less, web/src/less/setting-dialog.less
allow to search member and update members' password
A known style issue...
=> feat: member management enhancement

web/src/App.tsx, web/src/less/loading.less, web/src/pages/Loading.tsx, web/src/router/index.tsx
update route with dynamic lazy loading with fallback with simple loading
=> feat: dynamic lazy loading route with simple loading page

web/src/components/Settings/MemberSection.tsx, web/src/components/common/Dropdown.tsx
Before
https://user-images.githubusercontent.com/118022040/204652571-926a2020-b718-419c-b371-fad37e9b117a.mov
After
https://user-images.githubusercontent.com/118022040/204652630-7ce8dd25-ffe7-41b0-8e1f-9d9c2f3e11b9.mov
=> fix: member menu dropdown position

api/user_setting.go, web/src/components/Settings/PreferencesSection.tsx, web/src/i18n.ts, web/src/locales/de.json, web/src/pages/Auth.tsx, web/src/types/i18n.d.ts
This pull request refers to the issue #545 
In case you are wondering "_de_" is the official ISO 639-1 code for German.
This is one of my first open-source pull requests, so feedback is warmly welcome.
I used the PR #547  as a template for this PR...
Feel free to ask any question. Thank you for this cool project 🙂
=> feat: add German i18n item

server/system.go, web/src/components/Settings/SystemSection.tsx, web/src/helpers/api.ts, web/src/locales/de.json, web/src/locales/en.json, web/src/locales/fr.json, web/src/locales/nl.json, web/src/locales/sv.json, web/src/locales/vi.json, web/src/locales/zh.json
=> feat: vacuum database in setting

web/src/components/UsageHeatMap.tsx
one possible suggestion for https://github.com/usememos/memos/issues/685
=> fix: update UsageHeatMap.tsx to account for daylight savings

web/src/less/code-highlight.less, web/src/main.tsx
=> fix: code highlight in dark mode

.github/workflows/uffizzi-build.yml, .github/workflows/uffizzi-preview.yml, docker-compose.uffizzi.yml
Hi, @boojack ~
Here is the PR addressing Previews with Uffizzi - [issue](https://github.com/usememos/memos/issues/646)
This is the [PoC](https://github.com/ShrutiC-git/memos/pull/1) for[ Uffizzi](https://www.uffizzi.com/) + Memos integration and this is how the [live preview](https://app.uffizzi.com/github.com/ShrutiC-git/memos/pull/1) looks like for the PR opened in my fork.
This PR adds GitHub workflows that trigger Uffizi preview environments for any PRs to this repo — a comment, like this [here](https://github.com/ShrutiC-git/memos/pull/1#issuecomment-1334845386), is also posted on the PR which will link you to the preview environment, making it easier for maintainers and contributors to easily navigate to the preview! The previews are ephemeral, so every new PR is built in a fresh …
=> feat: add Uffizzi Integration

.github/workflows/uffizzi-preview.yml
Bump up the version for reusable.yaml to v2
thanks, @boojack , this is just a version update to one of our action files. This will also check how the previews are looking.
=> Bump Version of reusable.yaml

web/src/less/preview-image-dialog.less
Added dark theme bg color to controls.
#693
=> added dark theme bg color to buttons

server/resource.go
=> fix: url resource filename decode

web/src/labs/marked/marked.test.ts, web/src/labs/marked/parser/DoneList.ts, web/src/labs/marked/parser/OrderedList.ts, web/src/labs/marked/parser/TodoList.ts, web/src/labs/marked/parser/UnorderedList.ts
Hi, small fix for #742 
is just a span wrapper around the "li-container" content.
=> fix: add a span as wrapper to fix whitespace

api/resource.go, store/db/migration/dev/LATEST__SCHEMA.sql, store/db/migration/prod/0.9/00__resource_visibility.sql, store/resource.go
This reverts commit b68cc085922a4551c6d493e9e9e0739831f8480c.
=> chore: revert "feat: add `visibility` field to resource (#743)"

web/src/components/Dialog/BaseDialog.tsx
before
https://user-images.githubusercontent.com/38493346/208220359-a515dc3b-e2eb-446d-86bb-270cab1c8f8e.mp4
after
https://user-images.githubusercontent.com/38493346/208220365-9815cc58-d441-4242-b144-2bd2658db820.mp4
=> fix: dialog close when draging from in to out

web/src/components/UsageHeatMap.tsx, web/src/pages/Auth.tsx
=> fix: heatmap popup showing after logging out

web/src/components/CreateShortcutDialog.tsx, web/src/components/ResourcesDialog.tsx, web/src/components/ResourcesSelectorDialog.tsx, web/src/components/Settings/SystemSection.tsx, web/src/components/UpdateAccountDialog.tsx, web/src/components/UpdateCustomizedProfileDialog.tsx, web/src/components/common/Selector.tsx, web/src/helpers/filter.ts, web/src/locales/de.json, web/src/locales/en.json, web/src/locales/es.json, web/src/locales/fr.json, web/src/locales/nl.json, web/src/locales/sv.json, web/src/locales/vi.json, web/src/locales/zh.json
tag type i18n chinese
custom server dialog
=> feat: i18n chinese

web/src/components/Editor/Editor.tsx, web/src/components/MemoEditor.tsx
=> feat: support `command + k` shortcuts insert []()

web/src/components/MemoEditor.tsx
=> fix: shortcuts should exclude the shift judgment

web/src/components/MemoEditor.tsx
https://user-images.githubusercontent.com/10083758/208689665-4abc13c7-1f68-4af6-a361-f3c614b64488.mov
=> feat: use shift+tab to unindent

.github/workflows/build-and-push-release-image.yml
#770
tested it local with buildx and act
=> feat: add arm/v7 to buildx platforms

server/tag.go, server/tag_test.go, store/tag.go, web/src/components/CreateShortcutDialog.tsx, web/src/components/CreateTagDialog.tsx, web/src/components/MemoEditor.tsx, web/src/components/TagList.tsx, web/src/components/UserBanner.tsx, web/src/helpers/api.ts, web/src/less/tag-list.less, web/src/store/index.ts, web/src/store/module/index.ts, web/src/store/module/memo.ts, web/src/store/module/tag.ts, web/src/store/reducer/memo.ts, web/src/store/reducer/tag.ts
=> feat: create tag dialog

web/src/less/auth.less
=> fix: fix css of input placeholder in auth page

.github/workflows/build-and-push-release-image.yml
=> chore: revert add `linux/arm/v7` to platforms

web/src/App.tsx
#812
think this is the easiest option
=> fix: prioritize user css by moving it to the body end

web/src/less/editor.less, web/src/less/memo-content.less
=> feat: enable word break

web/src/components/Memo.tsx, web/src/labs/marked/marked.test.ts, web/src/labs/marked/parser/CodeBlock.ts, web/src/less/memo-content.less, web/src/locales/en.json, web/src/locales/zh.json
=> feat: support code copy

store/shortcut.go
=> fix: missing creator id in shortcut cache

web/src/locales/de.json
fixed some inconsistencies, new strings
=> feat: update German translation

.github/workflows/issue-translator.yml
There's a lot of Chinese issues in this repo. This workflow automatically translates those issues, without modifying the original.
[https://github.com/marketplace/actions/issues-translator](https://github.com/marketplace/actions/issues-translator)
=> feat: issue translator workflow

server/memo.go, web/src/components/MemoEditor.tsx
=> feat: support empty content memo

web/package.json, web/src/components/CreateTagDialog.tsx, web/yarn.lock
reference: https://mui.com/joy-ui/react-text-field/
=> fix: use input instead of textfield

web/src/components/PreviewImageDialog.tsx
it's hard to touch the container div when image ratio be similar to device screen ratio
=> feat: support swipe to switch img on touchscreen

web/src/labs/marked/parser/CodeBlock.tsx
=> fix: show copy button on hover

server/resource.go
=> fix: pdf resource preview

web/src/locales/zh-Hant.json
Correct some translation of zh-tw, It is more in line with the language habits of traditional Chinese users
=> chore: update zh-Hant.json

web/src/locales/zh-Hant.json
To be in line with the language habits of traditional Chinese users
=> more translation correction to traditional Chinese

web/src/pages/Explore.tsx
=> feat: tag filter in explore

web/src/components/Editor/Editor.tsx, web/src/components/MemoEditor.tsx
before
https://user-images.githubusercontent.com/38493346/217267132-509d56e2-7232-4356-ab00-0eaa44fd4b28.mp4
after
https://user-images.githubusercontent.com/38493346/217267155-1c0151c3-d3ab-40ae-a4d0-aaf503c53c8e.mp4
=> fix: editor cursor not in view after smart editing

web/src/components/common/DatePicker.tsx
=> fix: DatePicker should say Wed instead of Web

.gitignore, .vscode/extensions.json, .vscode/project.code-workspace, web/.vscode/extensions.json, web/.vscode/settings.json
=> chore: setup project workspace for better DX

server/rss.go, web/src/components/MemosHeader.tsx, web/src/pages/Explore.tsx, web/vite.config.ts
1. use `# title` as rss item title
2. use system custom profile as rss title and description
3. rss link in explore page and user page
=> feat: more rss info

README.md
=> docs: add memos-import-from-flomo

web/src/less/not-found.less, web/src/locales/en.json, web/src/locales/zh.json, web/src/pages/NotFound.tsx, web/src/router/index.tsx
=> feat: better not found page

README.md
- adds short description about memo
- adds additional features to feature list
- updates formatting issues to make document more scannable
- adds short tagline
=> chore: make README more comprehensive

store/db/migration/dev/LATEST__SCHEMA.sql, store/idp.go
* add idp table to dev schema file;
* add related store file with new standard.
=> feat: introduce idp table

server/rss.go
=> feat: generate RSS item title and limit item count

.vscode/settings.json, docker-compose.uffizzi.yml, server/profile/profile.go, server/version/version.go, store/activity.go, store/db/db.go, web/src/pages/Auth.tsx, web/src/store/module/global.ts, web/src/store/reducer/global.ts
Rename the previous `dev` mode to `demo` mode, and change `dev` mode to not to seed the db.
=> feat(mode): add demo mode

api/user_setting.go, web/src/components/LocaleSelect.tsx, web/src/i18n.ts, web/src/locales/ko.json, web/src/types/i18n.d.ts
This adds translation data for Korean(한국어).
=> feat: add Korean translation

api/memo.go, api/user_setting.go, server/memo.go, store/memo.go, web/src/components/DailyMemo.tsx, web/src/components/DailyReviewDialog.tsx, web/src/components/Memo.tsx, web/src/components/MemoList.tsx, web/src/components/Settings/PreferencesSection.tsx, web/src/components/ShareMemoDialog.tsx, web/src/helpers/consts.ts, web/src/helpers/filter.ts, web/src/pages/EmbedMemo.tsx, web/src/pages/Explore.tsx, web/src/pages/MemoDetail.tsx, web/src/store/module/memo.ts, web/src/store/module/user.ts, web/src/types/modules/memo.d.ts, web/src/types/modules/setting.d.ts
* set memo content max size is 1MB;
* remove memo display time setting;
* move limit and offset to store.
=> chore: update memo service

web/src/components/CreateShortcutDialog.tsx
“handleAddFilterBenClick” -> "handleAddFilterBtnClick"
[#1147 ](https://github.com/usememos/memos/issues/1147)
=> fix: function name typo

web/src/components/CreateResourceDialog.tsx
=> fix: omission of long filename

web/src/components/AboutSiteDialog.tsx, web/src/components/GitHubBadge.tsx
=> chore: open url in other tabs

web/src/locales/en.json
I made very minor changes to the en.json file to fix some nitpicky issues.
=> feat: update en locale

web/src/components/ShareMemoDialog.tsx
The original sharing image generation method  is generated in startup. When the images is load incompletely , the shared image is incorrect.
So I change the timing of generation sharing image after user click image button.
preview:
=> fix: Incorrect sharing image gerneration (#1157)

web/src/pages/Home.tsx
=> fix: corners not rounded on memos-editor-wrapper

web/.vscode/settings.json
=> chore: fix unknown at rule @applyless(unknownAtRules)

web/vite.config.ts
use a constant for quick change devProxy config
=> refactor: declare  variable for devProxyServer

doc/CustomThemes.md
Outlines a simple way to change the background color of the memos app.
=> For Issue #981 Create CustomThemes.md

server/auth.go, web/src/components/Toast.tsx, web/src/pages/Auth.tsx
=> fix - login security issue 

api/openai.go, api/system_setting.go, plugin/openai/chat_completion.go, plugin/openai/text_completion.go, server/openai.go, server/server.go, server/system.go, web/src/components/AskAIDialog.tsx, web/src/components/CreateResourceDialog.tsx, web/src/components/Dialog/BaseDialog.tsx, web/src/components/Header.tsx, web/src/components/Settings/SystemSection.tsx, web/src/helpers/api.ts, web/src/types/view.d.ts
=> feat: implement openai integration

plugin/storage/s3/s3.go
=> fix: s3 custom path

web/src/components/Header.tsx, web/src/components/HomeSidebar.tsx, web/src/components/UsageHeatMap.tsx, web/src/less/home-sidebar.less, web/src/less/memo.less, web/src/less/search-bar.less, web/src/less/usage-heat-map.less, web/src/locales/en.json, web/src/locales/zh.json
=> chore: add heat map to sidebar

web/src/components/AskAIDialog.tsx, web/src/components/Dialog/BaseDialog.tsx
fixed the overflow of dialog-content-container
~~old~~
new
=> fix: overflow of dialog-content-container

web/src/helpers/filter.ts, web/src/locales/en.json, web/src/locales/zh.json
=> feat: allow to filter memos with resources

go.mod, go.sum
I was playing around with osv-scanner and discovered that your code is vulnerable to GO-2023-1571 and I thought I'd prepare this PR to fix it for you.
=> Fix  for GO-2023-1571 vulnerability

plugin/openai/chat_completion.go, plugin/openai/text_completion.go
=> fix: request body format in openai api

web/src/components/AskAIDialog.tsx
=> chore: update ask AI trigger

Dockerfile
=> chore: expose port in dockerfile

web/src/locales/zh-Hant.json
update zh-tw translation to new file format
=> feat: update zh-tw translation to new file format

server/resource.go
Avoid unexpected filename injection.
=> refactor: build storage key

web/src/components/MemoEditor.tsx
=> chore: remove editor shortcuts

web/src/components/ResourceCard.tsx
=> feat: allow resource title mutiple line

web/src/components/AskAIDialog.tsx, web/src/components/MemoEditor.tsx, web/src/components/Settings/SystemSection.tsx
close https://github.com/usememos/memos/issues/1287
=> fix: handle IME mode in editor

web/src/pages/ResourcesDashboard.tsx
there is bug in the dropdown
fixed
=> fix: the dropdown be coverd

web/src/components/Header.tsx
Adding specific ids can help quickly locate elements and facilitate the customization of css and js. (I really need this!)
=> chroe: add ids for header elements

web/src/pages/MemoDetail.tsx
=> fix: show full content in detail page

web/src/components/Memo.tsx
=> fix: make creation time a link to the detail page

api/resource.go, api/system.go, api/system_setting.go, server/memo.go, server/resource.go, server/system.go, store/db/migration/dev/LATEST__SCHEMA.sql, store/resource.go, web/src/components/Settings/StorageSection.tsx, web/src/components/UpdateLocalStorageDialog.tsx, web/src/types/modules/system.d.ts
=> feat: support local storage

web/src/labs/marked/parser/Blockquote.tsx
=> fix: markdown support in blockquote

web/src/less/preview-image-dialog.less
=> fix: image preview dialog overlapping

web/src/pages/ResourcesDashboard.tsx
=> chore: update list switch style

web/src/pages/ResourcesDashboard.tsx
=> feat: add empty placeholder when search result is empty

web/src/pages/ResourcesDashboard.tsx
=> feat: empty selected resource when search resource

web/package.json, web/src/components/ResourceCard.tsx, web/src/css/tailwind.css, web/tailwind.config.js
=> feat: limit the num of lines for filename

web/src/components/UserAvatar.tsx
=> fix: logo img rounded

web/src/locales/sl.json
Please include it in next release.
=> Added slovenian translation.

web/src/components/LocaleSelect.tsx, web/src/locales/sl.json
Thank you for the update. Found some typos and fixed them. Also changed some string to better fit with the content.
=> Updated Slovenian translation

web/src/components/MemoEditor.tsx, web/src/components/PreviewImageDialog.tsx, web/src/components/ShareMemoDialog.tsx, web/src/components/ShortcutList.tsx, web/src/components/TagList.tsx, web/src/components/UsageHeatMap.tsx, web/src/less/share-memo-dialog.less, web/src/pages/MemoDetail.tsx, web/src/pages/ResourcesDashboard.tsx
=> chore: add usage into heatmap

web/src/components/Settings/StorageSection.tsx
Fixes #1471 
I think it needs to be cherry-picked to the latest release.
=> fix: unexpected reset of the storage setting

web/src/locales/ko.json
- added missing translation data into ko.json
- synced the JSON file key order of ko.json with en.json
- removed unused translation data
=> feat: update and refactor Korean translation data

test/store/resource_test.go
This PR will add some unit test cases to Backend test
Test cases:
- create a resource
- find a resource by a correct name
- find a resource by an incorrect name
- find a resource by a CreatorID
- find a resource by an incorrect CreatorID
- delete a resource
- delete a non-existent resource
=> feat: add resource backend unit test

web/src/pages/DailyReview.tsx
=> fix: incorrect date parsing

web/src/components/CreateResourceDialog.tsx, web/src/components/MemoEditor.tsx
=> fix: toast overload max size error

web/src/locales/ko.json
This PR updates Korean translation data.
=> feat: update Korean translation

store/db/migration/dev/LATEST__SCHEMA.sql
Add a new table `memo_relation`:
* `memo_id` is the id of source memo;
* `related_memo_id` is the id of related memo;
* `type` is the type of relation: "REFERENCE" | "ADDITIONAL"
=> chore: add memo_relation

README.md
- add: https://github.com/BarryYangi/MemosGallery
A simple gallery static page based on the memos api, I think it might be useful for some people, so I just post it up. Close this if not necessary.
=> docs: update readme with MemosGallery

web/src/components/MemoList.tsx
Adds infinite scrolling for memos on home page, no need to press for more memos each time.
Resolves #1599.
=> feat: add infinite scroll for memos

web/src/components/CreateResourceDialog.tsx, web/src/pages/ResourcesDashboard.tsx
=> feat: support file sorting when uploading

web/src/components/UserBanner.tsx
=> chore: show server name instead of "MEMOS"

web/src/components/MemoList.tsx
close #563 #1524
In #1524, the author has not responded for a long time. So I submit the PR.👀
=> fix: unexpected empty lines when copying-pasting

server/rss.go
=> fix: resource url in rss

web/src/components/kit/DatePicker.tsx
It's a feature request from Telegram group, which is highlight the date with memos in the DatePicker.
Below is the screenshot for this feature:
=> Highlight the DatePicker's date with memos

server/auth.go, web/src/components/Memo.tsx, web/src/components/MemoEditor/RelationListView.tsx, web/src/components/MemoEditor/ResourceListView.tsx, web/src/components/Settings/SystemSection.tsx, web/src/components/UsageHeatMap.tsx, web/src/store/module/global.ts
=> fix: initial system locale

server/memo.go
=> fix: patch memo visibility

web/src/components/MemoResourceListView.tsx, web/src/components/ResourceCover.tsx, web/src/helpers/utils.ts
=> fix: add thumbnail param using `URLSearchParams`

server/resource.go
There's no more description here, everything's shown in the code.
=> fix: concurrent counter operates

README.md, docs/custom-themes.md, docs/deploy-with-render.md, docs/development-windows.md, docs/updates.md, docs/windows-service.md
=> chore(revert): retire demo site

api/memo.go, server/memo.go, server/tag.go, store/memo.go
Add ability to search in the backend
=> Add support for content search

web/src/components/CreateIdentityProviderDialog.tsx
=> fix: sso templates

web/src/locales/ko.json
fixes some issues with Korean localization.
=> feat: update korean localization

api/user.go, setup/setup_test.go
The minimum length of the password is 3, but the error message given to the front end is 6
=> chore: modify the error message when registering a Host user

server/memo.go
fix https://huntr.dev/bounties/3ff3325a-1dcb-4da7-894d-81a9cf726d81/
=> fix: pin memos of other people

web/src/locales/vi.json
chore: modify some text for vi.json (Vietnamese)
=> chore: update vi.json locale

api/v1/auth/auth.go, api/v1/system.go, api/v1/user.go, test/server/server.go, web/src/components/DemoBanner.tsx, web/src/pages/Auth.tsx
=> chore: update auth page

web/src/pages/Auth.tsx
Maybe close https://github.com/usememos/memos/issues/1923
=> chore: remove auto signout in auth page

api/v1/openai.go, api/v1/system_setting.go, api/v1/v1.go, go.mod, go.sum, server/server.go
- add three API
/openai/chat-completion(old)
/openai/enabled(old)
/openai/chat-streaming
- revert the OpenAI config setting
- skip  chat-streaming API timeout
=> feat: implement memos chat backend function

api/v1/memo.go
In `/api/v1/memo`, the params `visibility` can be set as any values, which will cause anonymous request to fetch memos not `PUBLIC`.
=> fix: visibility param override the user auth state

web/src/components/MemoRelationListView.tsx
Simplified the arrow function in the map function by removing the curly braces and the return keyword, since it only has one expression.
=> chore: update MemoRelationListView.tsx

api/v1/jwt.go, api/v1/system.go, server/server.go, store/db/db.go
=> chore: update db connection params

web/src/components/Header.tsx, web/src/router/index.tsx
- Added check system.disablePublicMemos for non authorized users.
If user is anonymous and disablePublicMemos is on, then redirect to auth page 
- hide link to explore on sidebar for non authorized users.
=> feat(security): disable access for anonymous users, when disablePublicMemos is true

web/src/pages/ResourcesDashboard.tsx
=> fix: delete multiple resources, close #1986

api/v1/system.go, api/v1/system_setting.go, web/src/components/Settings/SystemSection.tsx, web/src/locales/en.json, web/src/locales/zh-Hans.json, web/src/store/module/global.ts, web/src/types/modules/system.d.ts
This PR add support for config `AutoBackupInterval` in system setting page, which was noticed on #1950 .
=> feat: add AutoBackupInterval in SystemSetting

api/v1/memo.go, api/v1/system.go, api/v1/user.go, test/server/system_test.go, web/src/components/Header.tsx, web/src/components/Memo.tsx, web/src/components/MemoList.tsx, web/src/components/ShareMemoDialog.tsx, web/src/components/UsageHeatMap.tsx, web/src/components/UserBanner.tsx, web/src/components/kit/DatePicker.tsx, web/src/helpers/api.ts, web/src/helpers/consts.ts, web/src/pages/EmbedMemo.tsx, web/src/pages/Explore.tsx, web/src/pages/Home.tsx, web/src/router/index.tsx, web/src/store/module/global.ts, web/src/store/module/memo.ts, web/src/store/module/tag.ts, web/src/store/module/user.ts, web/src/types/modules/memo.d.ts, web/src/types/modules/shortcut.d.ts, web/src/types/modules/tag.d.ts
#1916
- replaced user Id with username in links
- I had to do a bit of refactoring on the frontend and backend
=> feat: use username instead of uid

web/src/locales/hr.json, web/src/locales/ja.json, web/src/locales/ko.json, web/src/locales/pt-BR.json
fix src/pages/ResourcesDashboard.tsx(255,24): error TS2345: Argument of type '"resource.clear"' is not assignable to parameter of type 'Translations'.
=> fix: add resource.clear to translate

api/v1/jwt.go, api/v1/rss.go, api/v1/user.go, web/vite.config.ts
=> fix: rss route

web/src/locales/ja.json
=> chore: update ja.json

.github/workflows/build-and-push-release-image.yml, .github/workflows/build-and-push-test-image.yml
=> revert: chore: update build docker image actions

web/package.json, web/pnpm-lock.yaml, web/src/components/MemoEditor/Editor/TagSuggestions.tsx, web/src/components/MemoEditor/Editor/index.tsx
Closes: https://github.com/usememos/memos/issues/1858
Follow-up PRs ideas:
- using tab key to complete top suggestion
- key up/down to selection an option
<br />
_(github `@` mentions as more/less reference)_
Suggestions are visible:
- after pressing a character or backspace
- (never after a mouse click or cursor key press)
- when a current word has one and only one `#` character
- and that `#` is the first character in a current word
Suggestions are placed relative to the `#` character (not caret)
<br /><br />
<br /><br /><br />
<br /><br />
During implementation a bit of internal goal emerged to not complicate existing `Editor.tsx` component with calculations of suggestion box positioning, figuring out when to show or hide, getting partially written tag name at cursor position... …
=> feat: tag suggestions

web/src/labs/marked/parser/CodeBlock.tsx
=> fix: remove translate hook in code block

server/telegram.go, web/src/components/CreateTagDialog.tsx, web/src/locales/de.json, web/src/locales/en.json
I went through some of english and german localizations to correct or add minor things.
But also added `invalid-tag-name` to `en.json`. Which also means it should be translated elsewhere.
=> fix: minor spelling and wording changes for en and de 

web/src/locales/nl.json
Updated some weird translations I did before, and added new ones for new keys found in the English file.
I ignored some keys that don't seem to be used in the UI.
=> updated Dutch translation

web/src/components/CreateTagDialog.tsx, web/src/locales/en.json, web/src/locales/zh-Hans.json
=> chore: update zh-Hans translations for "Tag suggestions"

api/v1/system_setting.go, api/v1/user_setting.go, docker-compose.dev.yaml, plugin/telegram/bot.go, plugin/telegram/callback_query.go, plugin/telegram/message.go, store/user_setting.go
Some minor cleanup found when implementing an unsuccessful feature, may be unnecessary but good to have
=> chore: minor cleanup

scripts/build.ps1, scripts/build.sh
update developer build scripts, bringing feature parity between platforms.
=> chore: update build scripts

web/src/components/MemoEditor/Editor/TagSuggestions.tsx, web/src/less/memo-editor.less
Closes
https://github.com/usememos/memos/issues/2138
https://github.com/usememos/memos/issues/2139
=> fix: tag suggestions positioning

api/v1/memo.go, api/v1/v1.go, plugin/telegram/api_send_message.go, server/server.go
This PR add a new feature, which'll send a notification by Telegram bot to users who bind a Telegram UserID. By this feature, users could fetch the updates in the Memos server without manually refresh the web page.
=> feat: notify by telegram while new memo create by HTTP

web/src/components/kit/DatePicker.tsx
This PR contains two small optimization in DatePicker:
- Add two buttons to increase/decrease year.
- Add padding 0 on the month to keep the buttons position.
=> chore: better date picker

web/src/components/MemoEditor/Editor/index.tsx, web/src/components/MemoEditor/index.tsx
Back from some busy days....
This PR is related to the issue #2198 .
@boojack @eMUQI
=> feat: optimize the logic of the checkbox button.

web/src/locales/fr.json
=> chore: update fr.json

web/src/locales/zh-Hans.json
Currently translated at 100.0% (315 of 315 strings)
Translate-URL: https://hosted.weblate.org/projects/memos-i18n/english/zh_Hans/
=> chore: translated with Weblate

store/db/mysql/migrator.go
Currently, while using *MySQL* as db driver in `dev` mode, it always do migration on boot, this caused all data will be erase by the migrate SQL `drop table ....`.
This PR just fixes this bug by detect if the tables always exists, just like check the db file is exists in *SQLite*
=> fix: migration always in mysql

store/db/mysql/activity.go, store/db/sqlite/activity.go
This PR just fix a small bug ( maybe it's a new feature), that while we create `Activity`, the `Id`, `CreatedTs` attributes has no affect.
=> fix: create activity without some attributes 

store/activity.go, store/db/mysql/activity.go, store/db/sqlite/activity.go, store/driver.go
This PR just add `ListActivity` to store, which will used to export/import between drivers.
=> feat: add support for ListActivity

store/db/mysql/memo_organizer.go, store/db/sqlite/memo_organizer.go, store/driver.go, store/memo_organizer.go
This PR just add `ListMemoOrganizer` to store, which will used to export/import between drivers.
=> feat: add support for ListMemoOrganizer

cmd/copydb.go
This PR add a new feature to copy data between drivers, such as from `SQLite` to `MySQL`.
=> feat: copy data between drivers

web/src/locales/de.json
Currently translated at 99.6% (312 of 313 strings)
Translate-URL: https://hosted.weblate.org/projects/memos-i18n/english/de/
=> chore: translated using Weblate (German)

api/v1/auth.go, web/src/helpers/api.ts, web/src/locales/en.json, web/src/locales/zh-Hans.json, web/src/pages/SignIn.tsx
Many user complains that we should keep the session forever, but currently, we're only keep it for 7 days. So I just add a option for it, and you can change the behavior when sign in.
=> feat: add support for remember sign in

api/v1/system.go, server/profile/profile.go
This is a critical PR that fix a bug which will cause the filed of `Profile` leaked without any authorize, such as database DSN.
=> fix: some fields of profile leaked without auth

web/src/locales/hr.json
Currently translated at 87.5% (274 of 313 strings)
Translate-URL: https://hosted.weblate.org/projects/memos-i18n/english/hr/
=> chore: translated using Weblate (Croatian)

web/src/components/MemoEditor/Editor/TagSuggestions.tsx
Better tag suggestion as mentioned in issue #2397
At first I tried to implement Levenshtein Distance Fuzzy Sort but I found this method more reliable.
=> feat: Better tag suggestion

web/src/locales/pt-BR.json
Currently translated at 100.0% (314 of 314 strings)
Translate-URL: https://hosted.weblate.org/projects/memos-i18n/english/pt_BR/
=> chore: translated using Weblate (Portuguese (Brazil))

web/src/components/MemoEditor/ActionButton/TagSelector.tsx, web/src/components/MemoEditor/index.tsx
Quick tweak to use IconButton for the Memo editor helpers to keep a more consistent look
=> tweak(web): use iconbutton for editor helpers

api/v2/user_service.go
This PR fix a bug that the `username` for `ListUserAccessTokens` has no effect.
=> fix: list token for others failed

web/src/components/MemoEditor/index.tsx
=> fix: missing relation after post comment

docker-compose.dev.yaml
This PR modify the `docker-compose.dev.yml` to facilitate developers.
=> chore: docker compose dev

web/src/components/UsageHeatMap.tsx, web/src/utils/i18n.ts
This PR add a new feature, that makes Monday as the first day of week, while `locale` is `zh-Hans` or `ko`.
=> feat: week from monday in heatmap for zh-Hans and ko

web/src/components/Memo.tsx, web/src/components/MemoList.tsx, web/src/pages/Explore.tsx, web/src/pages/Home.tsx, web/src/store/module/memo.ts, web/src/store/reducer/memo.ts
Fix automatic data loading for various cases.
https://github.com/usememos/memos/assets/13242100/06fb5ef7-3505-4bb6-928b-d25c498640dc
=> fix: auto fetch more

web/src/labs/marked/parser/Heading.tsx
=> feat: support code in headings

web/src/components/Memo.tsx
=> feat: add share btn in more-action

api/v1/http_getter.go
=> chore: fix tag in  http_getter.go

README.md
The plugin usage effect is as follows, taking a shortcut as an example:
https://github.com/quanru/obsidian-periodic-para/assets/11739753/3d967527-b021-4a15-acd4-f5e6b0701a99
=> docs: add obsidian plugin

server/server.go
This PR include a small change, which skip API timeout while resource blob uploading, which is frequently reported as timeout.
This PR will closed #2513 and #1716 .
=> chore: skip timeout for blob upload

web/src/components/MemoResourceListView.tsx, web/src/components/ShareMemoDialog.tsx
Optimize the presentation of images and videos.
=> feat: optimize media resource display

api/v1/auth.go, api/v1/jwt.go, store/user_setting.go
This PR just remove all invalid tokens while it removed from the cookie by reasons other than logout, such as expired or any others.
=> chore: remove invalid access token from db

web/src/App.tsx
This is a small patch to remove the debug log in frontend.
=> chore: remove debug log

store/db/mysql/resource.go, store/db/postgres/resource.go, store/db/sqlite/resource.go
In the latest version, the relationship between Resource and Memo has changed. Telegram bot handler need to fix to work for that.
=> fix: attachments send from telegram lost

web/src/components/ShareMemoDialog.tsx
=> fix: date format in share memo dialog(#2668)

web/src/components/ShareMemoDialog.tsx
=> fix: eslint check failure after fixing #2672

web/src/components/ShareMemoDialog.tsx, web/src/locales/en.json, web/src/locales/es.json, web/src/locales/fr.json, web/src/locales/it.json
Allows for exporting individual Memos as Markdown files from the "Share Memo" dialog
=> feat: export Memos as Markdown FIles

api/v2/memo_relation_service.go
=> fix: duplicated/reflexive relation in v2 api.

store/db/mysql/resource.go
=> fix: set memo resources error in mysql

web/src/store/module/global.ts
The user settings(locale, appearance) are not in use when restart broswer
=> fix: change use-set priority

web/src/components/UserBanner.tsx
=> fix: display system logo in user banner if user not logged in

web/src/components/MobileHeader.tsx
=> fix: apply customized profile name in mobile header

api/v1/auth.go
If password login is disabled in the system configuration, the "signup" in the "/auth" page disappears, but the user can manually enter "/auth/signup" to access the system by creating a new user.
=> fix: signup is not allowed if password login is disabled

web/src/components/ActivityCalendar.tsx
=> fix: incorrect timeline month display

store/db/mysql/mysql.go
fix https://github.com/usememos/memos/issues/2837
=> fix: use mysql to parse dsn

api/v2/auth_service.go
Discussed here: https://github.com/usememos/memos/commit/c5a5f67fdb6944e49850aed6b04d5f3c33245dd4#r138097404 
And I also fixed an issue about #2776 in api/v2.
=> fix: role error in api/v2 when the first user registers

web/src/pages/About.tsx
=> chore: fix typo in About.tsx

web/src/pages/MemoDetail.tsx
related pr: #2809
related issue: #2868
=> feat: add notice when sharing private links in MemoDetail

server/integration/telegram.go
I have retrieved the 'workspaceSetting' and compared it, then handled to expose the error message. Please review the code.
#3036
=> fix: check disallow public memo in Telegram(#3036)

web/src/locales/ko.json
Currently translated at 95.1% (292 of 307 strings)
Translate-URL: https://hosted.weblate.org/projects/memos-i18n/english/ko/
=> chore: translated using Weblate (Korean)

web/src/locales/fr.json
Currently translated at 100.0% (293 of 293 strings)
Translate-URL: https://hosted.weblate.org/projects/memos-i18n/english/fr/
=> chore: translated using Weblate (French)

web/src/pages/MemoDetail.tsx
=> chore: fix memo link

web/src/locales/tr.json
Currently translated at 100.0% (300 of 300 strings)
Translate-URL: https://hosted.weblate.org/projects/memos-i18n/english/tr/
=> chore: translated using Weblate (Turkish)

go.mod
=> fix: specify go toolchain in go.mod (fix #3252)

web/src/components/MemoEditor/hooks/useAutoComplete.ts
=> fix: editor IME composing event behavior

web/src/locales/zh-Hans.json, web/src/locales/zh-Hant.json
Currently translated at 100.0% (303 of 303 strings)
Translated using Weblate (Chinese (Simplified))
Currently translated at 100.0% (303 of 303 strings)
Translate-URL: https://hosted.weblate.org/projects/memos-i18n/english/zh_Hans/
Translate-URL: https://hosted.weblate.org/projects/memos-i18n/english/zh_Hant/
=> chore: translated using Weblate (Chinese (Traditional))

web/src/locales/zh-Hans.json
Currently translated at 100.0% (303 of 303 strings)
Translate-URL: https://hosted.weblate.org/projects/memos-i18n/english/zh_Hans/
=> chore: translated using Weblate (Chinese (Simplified))

web/src/locales/hu.json
Currently translated at 98.6% (299 of 303 strings)
Translate-URL: https://hosted.weblate.org/projects/memos-i18n/english/hu/
=> chore: translated using Weblate (Hungarian)

web/src/i18n.ts, web/src/locales/mr.json
I have tested this on my local system and it's working.  These translations are downloaded from weblate. 
Thanks a lot for creating memos btw.
=> feat(i18n): added marathi(mr) translations

web/src/locales/mr.json
Currently translated at 100.0% (255 of 255 strings)
Translate-URL: https://hosted.weblate.org/projects/memos-i18n/english/mr/
=> chore: translated using Weblate (Marathi)

web/src/components/MemoEditor/ActionButton/AddMemoRelationButton.tsx
Was using the wrong uniqby queue
=> fix: update uniqby key

web/src/store/v1/memo.ts
- Looks like its a copy by reference issue where two things are manipulating the same data at the same time.
- Used the good old spread to stop this happening
=> fix: copy by reference

web/src/components/HomeSidebar/TagsSection.tsx, web/src/components/MemoEditor/ActionButton/TagSelector.tsx, web/src/components/MemoEditor/MemoEditorDialog.tsx, web/src/components/RenameTagDialog.tsx, web/src/store/v1/tag.ts
…ponents to pass in those params needed
- Updated the useTagStore fetchTags function to now accept a user and location and it handles the filtering internally
- updated all the places fetchTags was called to pass through the user and location where applicable
Looks to solve the issue where in certain circumstances it finds any public tags
=> chore: update fetch tags args

server/router/api/v1/resource_service.go
=> fix: add charset=utf-8 for text content resources

server/router/api/v1/memo_service.go, web/src/components/MemoEditor/index.tsx
Close https://github.com/usememos/memos/issues/3658
=> fix: update mask of update memo

.github/dependabot.yml
=> chore: update dependabot schedule interval

web/src/components/MemoEditor/ActionButton/MarkdownMenu.tsx, web/src/components/Settings/AccessTokenSection.tsx, web/src/components/Settings/MemoRelatedSettings.tsx, web/src/components/Settings/SSOSection.tsx, web/src/components/Settings/WebhookSection.tsx, web/src/components/Settings/WorkspaceSection.tsx, web/src/locales/en.json, web/src/locales/pt-PT.json, web/src/pages/Setting.tsx
Also add pt-PT translation for them
=> chore: allow some hardcoded strings to be translated

store/db/mysql/memo.go
Discussion: https://github.com/orgs/usememos/discussions/4062 and potentially this issue https://github.com/usememos/memos/issues/4105
The mysql syntax is missing a closing "
Note: I dont have a mysql db instance so this change is untested. Apologies for not testing this pr
=> fix: added missing "

web/src/components/UserStatisticsView.tsx
Fix #4121. Added a small part for a better view of first-time users. Make sure the overall consistency on the part of statistic view part.
=> feat: enhancement on UI/UX on user statistic view part.

web/src/components/ActivityCalendar.tsx
My apologies, the previous submission was affected by my custom implementation. Here is the code to fix the styling issue.
=> chore: style fix to #4151

web/src/components/PagedMemoList/PagedMemoList.tsx
Fix the failure of search conditions affected by pull-to-refresh.
=> fix: search conditions affected by pull-to-refresh

web/src/locales/zh-Hant.json
- Updated traditional chinese translation
=> chore: update zh-Hant

web/src/components/StatisticsView.tsx
Added a date picker to the activity calendar to make it easier to choose the year.
=> chore: add datepicker to calendar month

web/src/components/CreateShortcutDialog.tsx, web/src/components/Settings/MemoRelatedSettings.tsx, web/src/components/Settings/WorkspaceSection.tsx, web/src/locales/en.json, web/src/locales/zh-Hans.json
I add some Chinese localization config to file: web/src/locales/zh-Hans.json, and modified the code that referenced them on the page.
=> Chinese localization enhancements

web/src/components/HomeSidebar/TagsSection.tsx, web/src/components/Settings/StorageSection.tsx, web/src/locales/en.json, web/src/locales/zh-Hans.json
=> chore: update i18n chinese

web/src/components/Settings/MemberSection.tsx, web/src/locales/en.json, web/src/locales/zh-Hans.json
chore: update chinese i18n at member setting section
=> chore: update chinese i18n at member setting section

web/src/locales/zh-Hans.json
=> feat: update i18n zh-hans

web/src/locales/zh-Hans.json
=> chore: update chinese i18n for settings section

plugin/httpgetter/html_meta.go, web/src/components/MemoContent/Link.tsx
=> feat: support YouTube video thumbnail in link preview

web/src/router/index.tsx, web/vite.config.ts
=> feat: optimize initial load performance by implementing lazy loading and code splitting

web/src/components/RenameTagDialog.tsx, web/src/locales/zh-Hans.json
I think '重命名' is better than '标签重命名'
=> update zh-hans text  for rename-tag

web/src/components/Settings/WorkspaceSection.tsx
=> Fix: Allow admins to uncheck disallow password if applicable

web/src/components/BrandBanner.tsx, web/src/components/Navigation.tsx
I'm not sure if I'm missing something here, but this is my pass at fixing the top-left button so that it has `cursor: pointer;` on it properly by using a `<NavLink />`
*(This guy)*
Happy to make any edits here
=> Fix BrandBanner to use NavLink

plugin/storage/s3/s3.go
fixes https://github.com/usememos/memos/issues/4511
=> fix: aws-chunked encoding is not supported with the specified x-amz-content-sha256 value for some s3 providers

store/db/mysql/inbox.go, store/db/mysql/user.go, store/db/postgres/inbox.go, store/resource.go, store/test/resource_test.go
This PR addresses issue #4574.
Let me know if anything else needs to be updated. Thanks!
=> fix: remove errors.Wrap(nil)

server/server.go
Ensure the gRPC server is shut down
=> fix: shutdown gRPC server gracefully

web/src/locales/pt-BR.json
Added the new "attachments" message.
=> Update i18n for pt-BR locale

web/src/locales/pt-BR.json
added the new `user-sessions-section` translation section
=> Update i18n for pt-BR text

web/src/locales/cs.json
Used AI to translate from `en.json` locale
=> chore: update i18n for Czech locale

web/src/locales/id.json
Add missing Indonesian translations and update "to-do" translation for better consistency and natural language usage.
=> feat(i18n): update Indonesian (id) translations

web/src/locales/ru.json
Updated and corrected translation.  With adaptation to the sections used.
=> updated Russian translation

web/src/locales/id.json
fix(i18n): Improve Indonesian translation
=> fix(i18n): Improve Indonesian translation

web/src/locales/tr.json
Used AI to translate from en.json locale
=> chore(i18n): update turkish translation

web/src/locales/sl.json
Used AI to translate from en.json locale
=> chore(i18n): update slovenian translation

web/src/locales/pt-PT.json
Used AI to translate from en.json locale
=> chore(i18n): update portuguese translation

web/src/locales/ka-GE.json
Used AI to translate from en.json locale
=> chore(i18n): update georgian translation

web/src/locales/es.json
Used AI to translate from en.json locale
=> chore(i18n): update spanish translation

store/cache/cache.go
Hello, first time contributor here! 
I was recently having issues using memos on my armbian powered, armv7 tv-box. 
However, I saw this issue was already discovered by #4811:
**- Error:** there are some 64bit operations which are performed on the cache struct which cause a *panic: unaligned* error on 32-bit architectures, e.g.
`atomic.AddInt64(&c.itemCount, 1)`
**-Fix description:** The [atomic library docs](https://pkg.go.dev/sync/atomic) already reports that the **Int64** type is automatically aligned, in contrast with the usage of **int64**. Thus, the fix changes *itemCount* into an Int64, applying the equivalent function on this type directly instead of calling the atomic library functions. Example: 
`atomic.AddInt64(&c.itemCount, 1)`
becomes
`(&c.itemCount).Add(1)`
**-Testing:** The …
=> fix for issue 4811

web/src/components/HomeSidebar/TagsSection.tsx, web/src/components/TagTree.tsx, web/src/locales/en.json
Add an option to auto expand all subtags in tree mode.
https://github.com/user-attachments/assets/25b1c49a-7c14-4522-a908-82de497374c0
=> feat: add an option to auto expand subtags in tree mode

server/router/api/v1/test/memo_service_test.go
Added test that covers creating and retrieving memos with their attachments, reactions, and relations via the ListMemos method.
=> Add test for ListMemos
