usememos/memos

web/src/components/DailyMemo.tsx, web/src/components/DailyMemoDiaryDialog.tsx, web/src/components/MemoTrashDialog.tsx, web/src/components/Sidebar.tsx, web/src/components/UserBanner.tsx, web/src/less/about-site-dialog.less, web/src/less/daily-memo-diary-dialog.less, web/src/less/daily-memo.less, web/src/less/memo-content.less, web/src/less/menu-btns-popup.less, web/src/less/user-banner.less
=> chore: show daily memos view in sidebar

web/src/components/CreateShortcutDialog.tsx, web/src/components/Dialog/CommonDialog.tsx, web/src/components/ResourcesDialog.tsx, web/src/helpers/filter.ts, web/src/locales/en.json, web/src/locales/zh.json
Add i18n for resources and shortcuts.
For i18n with constant, I use i18n mark in constants, and render to text with `t` function in component. Wondering if there's a better solution.
=> chore: update i18n for shortcut filter

web/src/components/MemoList.tsx, web/src/components/ShortcutList.tsx, web/src/components/TagList.tsx, web/src/helpers/utils.ts, web/src/hooks/closeSidebar.ts
非常感谢大佬们写出这样牛逼的程序👍！我在移动端的使用过程中，发现当标签过多的时候，选择需要的标签后，需要上滑找到侧边栏的关闭按钮点击才能关闭掉侧边栏，查看选择标签的内容。有一些不太方便。
修改：点击快捷方式、标签、和列表区域时，会关闭掉侧边栏。
=> 添加移动端点击自动关闭侧边栏

web/src/components/MemoEditor.tsx, web/src/helpers/consts.ts
=> feat: editor tab support

web/src/labs/marked/index.ts, web/src/labs/marked/marked.test.ts, web/src/labs/marked/parser/Link.ts, web/src/less/memo-content.less
close #317 
link with code:
pure link:
---
use `decoration-1` with tailwind (`text-decoration-thickness: 1px`)
without `decoration-1`:
=> feat: inline code within link

web/src/components/ResourcesDialog.tsx, web/src/less/resources-dialog.less
I have done two things: 
- increase the width of the dialog. 
- add a tooltip to show the full resource name/type while hovering.
before:
after:
=> feat: resource dialog enhancements

api/resource.go, server/resource.go, store/resource.go, web/src/components/ChangeResourceFilenameDialog.tsx, web/src/components/ResourcesDialog.tsx, web/src/helpers/api.ts, web/src/less/change-resource-filename-dialog.less, web/src/less/resources-dialog.less, web/src/locales/en.json, web/src/locales/vi.json, web/src/locales/zh.json, web/src/services/resourceService.ts, web/src/store/index.ts, web/src/store/modules/resource.ts, web/src/types/modules/resource.d.ts
https://user-images.githubusercontent.com/31177490/198781557-6652f430-1b34-4dfa-a672-807832d33633.mp4
Maybe a strong review is needed, thanks!
=> feat: patch resource filename

web/src/components/Memo.tsx
||pinned|unpinned|
|---|---|---|
|new|<img width="151" alt="image" src="https://user-images.githubusercontent.com/17293034/199307446-4f70d8e3-2539-44d8-967e-a8a912c2e691.png">|<img width="158" alt="image" src="https://user-images.githubusercontent.com/17293034/199307517-e5fe9a22-80ef-4a52-81d3-aa9645ef190e.png">|
|old|<img width="153" alt="image" src="https://user-images.githubusercontent.com/17293034/199308063-b3466e5a-b21c-4671-a8ba-a1b650514aec.png">|<img width="148" alt="image" src="https://user-images.githubusercontent.com/17293034/199308115-b160d1cc-3c49-4a64-a6e5-788cab37a7d2.png">|
The old unpinned Memo's pin button looks like a disabled button. Maybe we can change the color a bit.
=> chore: pin button color

web/src/components/MemoEditor.tsx, web/src/less/editor.less, web/src/less/memo-editor.less
=> feat: update editor style

web/src/components/Memo.tsx, web/src/components/MemoFilter.tsx, web/src/components/MemoList.tsx, web/src/services/locationService.ts, web/src/store/modules/location.ts
https://user-images.githubusercontent.com/31177490/201522152-c45aefaa-96cc-4256-b66a-cce93e8e0123.mp4
There are no clickable tag/label for the private memos.  Should we add?
=> feat: visibility click filter

web/src/store/modules/location.ts
Import `qs` to parse the query string instead of `URLSearchParams` which cannot parse the duration object.
https://user-images.githubusercontent.com/31177490/201601121-59dceb3c-5051-405a-ae27-a362aab4a015.mp4
https://user-images.githubusercontent.com/31177490/201601134-e96182ca-dc79-4f78-be12-bfd29b848519.mp4
=> fix: duration query string

web/src/less/memo-card-dialog.less
I think white is more suitable for the current style.
=> chore: change memo card's bg color

web/src/components/ShareMemoImageDialog.tsx, web/src/less/share-memo-image-dialog.less
=> feat: update sharing memo image

web/src/labs/marked/parser/Link.ts
```markdown
[Predicate (mathematical logic)](https://en.wikipedia.org/wiki/Predicate_(mathematical_logic))
```
+ Now: [Predicate (mathematical logic)](https://en.wikipedia.org/wiki/Predicate_(mathematical_logic)))
+ Should: [Predicate (mathematical logic)](https://en.wikipedia.org/wiki/Predicate_(mathematical_logic))
=> fix: abnormal link regex

web/src/less/memo.less
With a double click on edit/pin button, you can get selection on tooltip text. It doesn't look good.
https://user-images.githubusercontent.com/118022040/203890748-5901c054-6f83-4834-94c7-17ee84e4d404.mov
=> fix: make tooltip text no-selecting

web/src/components/Memo.tsx
src of the img tag is  `/o/get/image?url=http://localhost:3000/o/r/1/image.png`
but 
src in the markdown content is `['http://localhost:3000/o/r/1/image.png']`
So `findIndex` function cannot find the correct index.
=> fix: get markdown image from backend

web/src/less/memos-header.less
Dropdown was disappearing when the mouse was still on it.
Common tools bar has the same z-level, so it overlaps the dropdown.
https://user-images.githubusercontent.com/118022040/204094779-827e679b-4c3d-47a3-96c8-411a531bbccc.mov
=> fix: search bar dropdown disappearing

web/src/components/ShortcutList.tsx
when delete a shortcut which is apply for the filter, the filter remain but filter item disappear, and the list still remain filtered
=> fix: clear shortcut filter when delete this shortcut

web/src/helpers/filter.ts, web/src/labs/marked/parser/Tag.ts
when apply a shortcut using tag filter, only the first tag in content can be found.
For example..
result is 
it should be
=> fix: shoutcut tag filter handle mutiple tags

web/src/less/memo-editor.less
=> fix: selector dropdown position in fullscreen mod

server/user.go
Did not return the `UserSettingsList`
=> fix: no user settings returns when patch user

web/src/less/memo-editor.less
0.8.0
Upload a file with a long name
iphone SE
I can remove this file
```css
.resource-container {
max-width: 100%;
}
```
=> fix: resource-container overflow

api/user_setting.go, web/src/components/Settings/PreferencesSection.tsx, web/src/i18n.ts, web/src/locales/sv.json, web/src/pages/Auth.tsx, web/src/types/i18n.d.ts
This adds `swedish / svenska` translation for all current translatable strings.
=> feat: add swedish/svenska translation

web/src/locales/de.json
Switched to plural to make the difference between TAG(S) and TAG(E) clearer... Refers to #545
=> chore: update German translation

web/src/components/Settings/PreferencesSection.tsx, web/src/locales/de.json, web/src/locales/en.json, web/src/locales/es.json, web/src/locales/fr.json, web/src/locales/nl.json, web/src/locales/sv.json, web/src/locales/vi.json, web/src/locales/zh.json
I've changed the word 'Theme' in the 'Preferences' settings section to also be translated. Also added translation for all languages currently in main.
(yes, i know my branch name is 'dutch-locale'. it's the same as before, i'm lazy)
=> feat: add 'theme' to translation

api/resource.go, store/db/migration/dev/LATEST__SCHEMA.sql, store/db/migration/prod/0.9/00__resource_visibility.sql, store/resource.go
We now fetch resources (such as images) via the route `/o/r/:resourceId/:filename`. So everyone can get the image through the link.
This PR introduces a new field `visibility` in the `resource` model. It has the same meaning as the `visibility` field in `memo` model.
=> feat: add `visibility` field to resource

web/src/components/MemoEditor.tsx
Before: When text is selected in the range, the cursor is positioned at the current position + the length of the selected text
After: The cursor will be positioned at the start of the selected text content + TAB_SPACE_WIDTH
=> fix: incorrect cursor when text is selected in range

web/src/components/UsageHeatMap.tsx, web/src/locales/de.json, web/src/locales/en.json, web/src/locales/es.json, web/src/locales/fr.json, web/src/locales/nl.json, web/src/locales/sv.json, web/src/locales/vi.json, web/src/locales/zh.json
Translation for weekdays on the heatmap (top left)
Sources:
European languages: https://www.ema.europa.eu/en/documents/other/abbreviation-names-days-calendarised-blisters_en.pdf
Vietnamese: https://en.wikipedia.org/wiki/Date_and_time_notation_in_Vietnam
Chinese: https://improvemandarin.com/days-of-the-week-in-chinese/ and https://linguistics.stackexchange.com/questions/17157/weekday-abbreviations-in-multiple-languages
Let me know if any translation is incorrect!
=> feat: implement translation for days

web/src/components/SearchBar.tsx, web/src/less/search-bar.less
To solve the problem of displaying the active panel when the searchBar is focused after pressing `cmd+f`
=> feat: show active panel when searchBar is in focus

web/src/css/tailwind.css, web/src/less/auth.less, web/src/less/explore.less, web/src/less/home.less, web/src/less/memo-detail.less
When the height of the page changes and the scroll bar appears, the content layout in the horizontal drama of the page will jitter left.
Before:
https://user-images.githubusercontent.com/10083758/208902530-e6b151d7-c4fe-4716-92eb-4636a4aea61f.mov
After:
https://user-images.githubusercontent.com/10083758/209065958-b2f6ac8a-a4c4-47b9-b7b0-2f77f1ade826.mp4
=> feat: prevent page jitter caused by the presence of scroll bars

web/src/components/ShareMemoDialog.tsx
resolves #930 
not all translations have a text for this, so it may default to English.
=> chore: added translation for copy memo link

web/src/less/memo-resources.less
when upload image scale not 1:1, it look like :
And it can scroll inside container.
After fix:
=> fix: round corner issue in resource blocks

server/resource.go
Problem is video (and audio) can't play on safari and on iOS webapp mode .
video resource also can't play when direct request the url like 
```
https://memos_host/o/r/<id>/filename.mp4
```
a error in console is `Failed to Load Resource, Plugin Handled Load`.
And after some searching ,it looks like current `c.Stream()` function cannot response request with Header `Range: bytes=0-1` correctly. According to [rfc7233](https://www.rfc-editor.org/rfc/rfc7233#section-4.1) it should respone with code 206.And `c.Stream()` function also can't return part of content, it can be test use the following code:
```
curl --range 0-99  https://memos_host/o/r/<id>/filename.mp4 -o output.mp4
```
So for the video&audio content I use `http.ServeContent` Instead of `Stream()` to return the data because it …
=> fix: video and audio can't play on safari

.github/workflows/build-and-push-release-image.yml, .github/workflows/build-and-push-test-image.yml
Signed-off-by: Ruihang Xia <waynestxia@gmail.com>
Closes #1005 
anchor `setup-buildx-action@v2` to version `v0.9.1`
=> chore(build): anchor setup-buildx-action@v2 to version v0.9.1

api/storage.go, server/storage.go, store/db/migration/dev/LATEST__SCHEMA.sql, store/storage.go, web/src/types/modules/storage.d.ts
Since the storage belongs to system setting and only the web host can access it, so the `creator_id`, `created_ts` and `updated_ts` fields are useless.
=> chore: remove unused fields of storage table

web/src/less/memo.less
When deleting an archived memo, I will be prompted "Delete!" after clicking the text button "Delete", but in the same colour. 
Typically such confirmation should be displayed in an eye-caching colour, especially red, to warn people before this kind of irreversible operations. 
So I suggest changing the property of the CSS class `.final-confirm` to fix that.
=> feat: use accent color when confirming deletion

web/src/less/preview-image-dialog.less
`z-index` of the `BaseDialog` is 1000.
=> fix: z-index of image preview

web/src/less/memo.less
Fixes #1217 by removing hidden overflow on memo-wrapper and adding top right border-radius to corner container.
=> fix: action button container not overflowing memo

web/src/labs/marked/parser/Link.tsx
Fixes #1162 by updating the link regex to pick up edge case with parentheses
=> Fix: Markdown hyperlinks with parenthesis take first closing parenthesis as final

api/storage.go, plugin/storage/s3/s3.go, server/resource.go, web/src/components/CreateStorageServiceDialog.tsx, web/src/types/modules/storage.d.ts
This pr added support for the s3 path.
If you want to upload your images to like `image` folder, you can set path variable to `path/`. (default value will be empty)
=> add support for s3 path

web/src/labs/marked/parser/Link.tsx
=> revert: Fix: Markdown hyperlinks with parenthesis take first closing parenthesis as final

web/src/labs/marked/parser/Br.tsx
fix warning due to parser br  missing prop key
[lists-and-keys.html#keys](https://reactjs.org/docs/lists-and-keys.html#keys)
=> fix: missing prop key

web/package.json, web/vite.config.ts, web/yarn.lock
reproduce:  navigate from the home page /  to /explore, then use the browser back button, navigate action will be failed and show a  warning console log.
how to fix: upgrade the react-router version above 6.8.1.
[react-router issue #9998](https://github.com/remix-run/react-router/issues/9998)
=> fix: navigate faild silently

web/src/components/AskAIDialog.tsx
#1297 
before loading answer
loading:
=> fix: Ask-AI history list reversed when loading answer

web/src/components/HomeSidebar.tsx, web/src/components/SearchBar.tsx
Currently should click twice when you want to input some words in search bar in mobile, so we should auto focus the input element when sidebar is shown or can also be said that the search button is been clicked.
=> feat: auto focus search bar when sidebar is shown (close #1269)

web/src/labs/marked/parser/Link.tsx
Hey, I had the same issue as in #1162 and I noticed that the fix was revert. Here's my PR to fix the issue.
Before:
After:
=> fix: Update markdown hyperlink regex

web/src/components/CreateTagDialog.tsx
current behavior
the tag list widget logic
=> fix: unified tag sorting logic

web/src/pages/ResourcesDashboard.tsx
There is bug in the resource dashboard. 
The bug cause the incorrectly calc for grid row height in safari. to fix it using `h-auto` intead of  `h-full` in container div.
fixed
=> fix: the incorrectly height of grid row in safari

Dockerfile
When the dependencies haven't changed, installing dependencies using cache is used when building a Docker image.
=> build: update dockerfile for using cache to speed up

api/storage.go, plugin/storage/s3/s3.go, server/resource.go, web/src/components/CreateStorageServiceDialog.tsx, web/src/types/modules/storage.d.ts
If using mobile app upload image, original image is very large
Aliyun OSS supports image processing, compression, and only needs to add a suffix, so add this option
```
{URLPrefix}/{filename}{URLSuffix}
https://xxx.com/test.png?x-oss-process=image/resize,h_100,m_lfit
```
https://help.aliyun.com/document_detail/183902.html
=> feat: add URLSuffix resource option with S3

server/memo.go
Something that I noticed on my instance was that I needed to lock users from posting publically, but didn't want to prevent my moderators from doing so. This patch allows moderators to bypass the visibility: private enforcement.
=> feat: allow instance moderators to post public via the API

web/src/css/global.css
This PR fixes #1495.
Now the font fallback list looks like:
- [system-ui](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#:~:text=MT%2C%20Harrington%2C%20fantasy.-,system%2Dui,-Glyphs%20are%20taken)
- Common western fonts (e.g. Helvetica, Arial, etc)
- Common Chinese fonts
- Emoji and symbols fonts
- [sans-serif](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#:~:text=URW%20Palladio%2C%20serif.-,sans%2Dserif,-Glyphs%20have%20stroke)
=> fix(css): reorder the font fallback list (#1495)

.github/workflows/build-and-push-release-image.yml, .github/workflows/build-and-push-test-image.yml
This PR will add a GHCR container image mirror during the test and release CI jobs.
Fixes #1502.
After merging this PR, release images will also contain a major and minor tag, so `v0.12.1` will be available at `0.12.1`, `0.12`, `0`. This is useful for users that want to pin the major or minor version, but don't care about the current patch version.
The package repository will be created automatically during the first run, but may default to `private` visibility. If so, you will need to:
1. Go to https://ghcr.io/usememos/memos
2. Package Settings
3. Change package visibility
4. Set to `Public`
After changing visibility, I'd also suggest that you go to this repo's homepage, click the settings cog on the right, then enable `Packages` on the homepage.
=> feat(ci): Add GHCR mirror and major/minor rolling tags

.github/workflows/build-and-push-release-image.yml
My previous PR #1503 used the git tag to determine the Docker tags, but it should have used the git branch. This PR will fix that! Sorry for the trouble
=> fix(ci): fix release builds not having any tags

plugin/storage/s3/s3.go
When uploading files without the old config.  Server url like "https://minio.test.com" would be converted to "https://bucketname.minio.test.com". For the self-host minio instance, the upload would get errors. With this config enabled, everything would just work perfectly! 
some resource related: https://stackoverflow.com/questions/67575681/is-aws-go-sdk-v2-integrated-with-local-minio-server
=> feat: add `HostnameImmutable` to aws endpoint config

README.md
I re-arranged the install docs a bit to separate them into Docker and hosted options:
https://usememos.com/docs
This also breaks the said link in the README. Most appropriate alternative would be this:
https://usememos.com/docs#installation
=> fix: the broken install docs link

web/.gitignore, web/src/components/MemoContent.tsx, web/src/components/Settings/PreferencesSection.tsx, web/src/locales/de.json, web/src/locales/en.json, web/src/locales/es.json, web/src/locales/fr.json, web/src/locales/it.json, web/src/locales/ko.json, web/src/locales/nl.json, web/src/locales/pl.json, web/src/locales/pt-BR.json, web/src/locales/ru.json, web/src/locales/sl.json, web/src/locales/sv.json, web/src/locales/tr.json, web/src/locales/uk.json, web/src/locales/vi.json, web/src/locales/zh-Hans.json, web/src/locales/zh-Hant.json, web/src/store/module/user.ts, web/src/types/modules/setting.d.ts
I added a auto collapse switch in preference setting,
By switching off, all memos will not collapse. If switching on, all memos that exceed certain words limit will collapse as usual.
=> Add auto collapse feature for all memos issue #1463

docs/updates.md
Added a document detailing how to update to the latest version of memos after deploying on fly.io
=> docs: upgrade on fly.io

web/src/components/MemoContent.tsx
MemoContent being part of "Memo" Component and Memo part of "Explore" page. MemoContent throws error and doesn't render without User states. Since user is "undefined" for visitor mode, destructuring user states to get localSetting is not possible. Hence adding further guard to check for visitorMode and making autoCollapse state "true" by default is the right choice.
=> fix: memo content availability for visitor mode

web/src/components/MemoEditor.tsx, web/src/helpers/utils.ts
Wanted to add this feature to prefill the memo editor content from the URL.
Had some trouble running the e2e tests, could someone tell me how to get them running so I can add tests if needed?
=> feat: read content from search params

web/src/components/AskAIDialog.tsx
When dialog is reappeared after being in a hidden state. Then reappeaning should block further body scrolling for consistent UX.
=> reappearing of dialog should add body scrolling class.

web/src/hooks/useEvent.ts
some code slipped past the eslint checks, this will stop other PRs from failing their frontend tests
=> fix: failed eslint checks

docs/development-windows.md, docs/windows-service.md, scripts/.air-windows.toml, scripts/build.ps1, scripts/start.ps1, server/profile/profile.go
Add preliminar Windows support for both development and production environments.
Default profile.Data will be set to `C:\ProgramData\memos` on Windows. Folder will be created if it does not exist, as this behavior is expected for Windows applications.
System service installation can be achieved with third-party tools, explained in docs/windows-service.md.
Not sure if it's worth using https://github.com/kardianos/service to make service support built-in.
This could be a nice addition alongside #1583 (add Windows artifacts)
=> feat: add preliminar Windows support

web/src/helpers/utils.ts
After scroll the page, the popup div of the UsageStatItem was wrong, like the screenshot below:
=> fix: wrong position of UsageStatItem's popup

common/image.go, server/resource.go, web/src/components/MemoResources.tsx
While publishing a large number of HD images, the memoe will take a lot of time to load.
So I just generate a smaller thumbnail while uploading image resources, and only load the thumbnail in the memo. If click on the image, it will load the original HD image lazy.
=> feat: add support for image thumbnail

web/src/components/ResourceCover.tsx, web/src/less/resource-cover.less
The resource dashboard now only show an icon for all resources. Change it to show the thumbnail while it was an image.
=> Show thumbnail in resource dashboard

server/resource.go
Thumbnail cache path haven't been create before write file, which will cause the new guys fail to get thumbnail always.
=> Fix fail to open file while generate thumbnail

web/src/components/Header.tsx, web/src/components/MobileHeader.tsx
Old:
When the width is md. the user interface has no search button and no home side.
- show the search button when the width is md
- fix error z-index
otherwise:
New:
=> fix: md without search icon

web/src/components/HomeSidebar.tsx
close: #1667 #1594
the Bug caused by touch textarea will tigger resize event in Android chrome🤔 I try to set `resize: none` or anything. But these didn't work. But I found to delete the resize function. all functions are working fine! 🤯
https://github.com/usememos/memos/assets/29306285/48d393d5-ab74-47f3-8002-330aaebcdae4
adjust width when opening search:
the error highlight fixed in #1699
=> fix: pop search when touch textarea in Android Chrome

web/src/components/MemoEditor/ActionButton/MemoVisibilitySelector.tsx
The memos visibility in `System Setting` must priority than the user'.
For example, while the user
- Set `Disable public memos` in `Admin-System-Settings` to true
- Set `Default memo visibility` in `Basic-Preferences-Preferences` to `Public to everyone`.
The new memos should use only `Private` visibility. But it shows `Public to everyone` on the memos create dialog, and not selectable.
=> Fix system memo visibility was replace by user's setting

server/resource.go, web/src/components/UpdateLocalStorageDialog.tsx
Currently, we use filename in the storage path. Because the filename comes from the user's input, it may cause some problems, such as:
- Same filename will replace each other.
- Characters in filename is difference between all OS. Valid name in Windows may cause problems in Linux.
So I replace the origin filename into a UUID which exists in the code. The new filename used to storage only, and the origin filename still save in the database for review and shown in UI.
=> Replace filename to publicid

web/src/pages/DailyReview.tsx
While the memos count more than DEFAULT_MEMO_LIMIT, there is a bug in DailyReview page, which will caused infinite request to `/api/memo`
=> fix: infinite loop while daily memos more than DEFAULT_MEMO_LIMIT

api/system_setting.go, api/user_setting.go, plugin/telegram/api_edit_message.go, plugin/telegram/api_get_file.go, plugin/telegram/api_get_updates.go, plugin/telegram/api_send_message.go, plugin/telegram/chat.go, plugin/telegram/download.go, plugin/telegram/file.go, plugin/telegram/handle.go, plugin/telegram/message.go, plugin/telegram/photosize.go, plugin/telegram/request.go, plugin/telegram/robot.go, plugin/telegram/update.go, plugin/telegram/user.go, server/memo.go, server/resource.go, server/server.go, server/system.go, server/telegram.go, server/user.go, store/user_setting.go
This PR add Telegram Bot support inside the Memos. Core features include:
- Support both text and photo message, include multiple photo message.
- One Telegram Bot need for whole Memos Server, every user can bind there Telegram UserID in UserSettings of Memos .
- Pull mode of Telegram Bot, which works on your office LAN or home NAS.
Because it's a large PRs, so some features will be added in next version, such as:
- Webhook mode of Telegram Bot, which for people who cannot touch Telegram API.
- Support message other than text and photos, such as File Message, Location Message, etc.
=> feat: implement telegram bot plugin

api/system_setting.go, plugin/telegram/download.go, plugin/telegram/request.go, plugin/telegram/robot.go, web/src/components/Settings/SystemSection.tsx, web/src/locales/en.json, web/src/locales/zh-Hans.json
This PR just close #1763 .
With this PR, we can config a *Telegram Robot Token* like `http..../bot<token>` to use a reverse proxy API for Telegram. Some config example like below:
- `http://telegram.myhost.com/bot<token>`
- `https://telegram.myhost.com/bot<token>`
The config **Must** satisfied with two rules:
- Start with `http`, both `http://...` or `https://...` are OK.
- End with `/bot<token>`, because we need to guest the [File Download URL](https://core.telegram.org/bots/api#file) by replace `/bot<token>` into `/file/bot<token>`.
After this PR has been merged, I'll update the document in [dotcom](https://github.com/usememos/dotcom)
=> feat: add telegram proxy support

docker-compose.dev.yaml, web/vite.config.ts
Run a dev environment with `docker compose -f docker-compose.dev.yaml up -d`, and keep no command console.
Before do that, do some setup command as below:
```bash
docker compose -f docker-compose.dev.yaml run api go install github.com/cosmtrek/air@latest
docker compose -f docker-compose.dev.yaml run web npm install
```
PS: If this proposal was approved, maybe we can move `docker-compose.dev.yaml` to `docker-compose.yaml`.
=> feat: add docker compose file for development

web/src/components/MemoList.tsx
Just fix #1759 .
How to reproduce this bug?
1. Initial a fresh Memos.
2. Feed some memo with script `feed.sh` below.
3. Open the home page, and click on the default tag filter `inbox`.
Now, you can see an infinite request in your API server.
feed.sh
```bash
!#/bin/sh
OPENID=YOUR-OPEN-ID-OF-MEMOS
for i in {1..111} ; do
m=$( expr $i % 5)
[ $m -eq 0 ] && curl -X POST "http://localhost:3001/api/memo?openId=${OPENID}" \
-H 'Content-Type: application/json; charset=utf-8' \
-d "{\"content\": \"`date +%Y-%m-%d_%H:%M:%S` ${i} Just test\"}"
[ $m -ne 0 ] && curl -X POST "http://localhost:3001/api/memo?openId=${OPENID}" \
-H 'Content-Type: application/json; charset=utf-8' \
-d "{\"content\": \"#tag${m}\n`date +%Y-%m-%d_%H:%M:%S` ${i} Just test\"}"
done
```
=> fix: infinite loop in home page

web/vite.config.ts
Base is the public basic path for development or production environment services. It defaults to "/", is an absolute path, and is modified to "./" to be a relative path available for nginx proxy.
=> fix: add public base path (#1748)

web/src/components/MemoList.tsx
While copy anything in Safari, there's always shown a dialog like below:
I have checked the relative code, and this bug may caused by the `copy-to-clipboard` module which `copy` inject depends on. This module use `document.execCommand("copy")` to copy text into clipboard, but this call will always return `false`, which will enter into `copy-to-clipboard`'s fallback code.
In the fallback code, the module try to use `window.clipboardData.setData` to copy first, if that failed, it'll use `prompt` dialog at last.
In Safari, there is no `clipboardData` on `window` object. But the copy event do.
I can't simply replace the `copy-to-clipboard` module, because maybe some others need that.
So I just make a hook around `copy` call. This hook will determine whether `window.clipboardData` is …
=> fix: copy-to-clipboard not works well in Safari

Dockerfile
We already disabled `CGO_ENABLED` in golang build, so the `musl-dev` which used to install `musl-libc` doesn't need any more. Just clean it from Dockerfile
=> chore: clean Dockerfile to exclude musl-dev

plugin/storage/s3/s3.go
This PR fixed #1756.
In #1230 we set an option `HostnameImmutable` to `true` for s3 SDK. But it'll break while use this SDK to upload to Aliyun OSS, which is wildly used.
Maybe we should split a `OSS` backend storage instead share with S3, but before that, we can fixed this issue ASAP.
=> fix: failed to upload OSS with S3 SDK

web/vite.config.ts
This reverts commit d205a7683a3ab55c7500fe3507b3f0e95265ea1e.
#1775 has changed the base path in `vite.config.js`, which will breaks all links in subpath , such as `/m/:memoid`.
=> revert: fix: add public base path (#1748) (#1775)

web/src/components/Settings/SystemSection.tsx
In `Admin-System` section of `Setting` page, some settings state always be changed unexpectedly without any toggle on it. These settings include:
This setting was changed unexpectedly because itself. 
While it was toggled, it only call server API and update `state` store in page, the value in `globalStore` was not affected.
But if the `globalStore` was changed by any other settings, it will reset the `state` store in page to the value cached in `globalStore`.
These two settings confused the local storage keys, so it changed each other while toggle.
=> fix: systemSetting in UI changed unexpectedly

plugin/telegram/api_answer_callback_query.go, plugin/telegram/api_edit_message.go, plugin/telegram/bot.go, plugin/telegram/callback_query.go, plugin/telegram/handle.go, plugin/telegram/inline_keyboard_button.go, plugin/telegram/update.go, server/telegram.go
This PR add a new feature, which provide ability to change/set memo's visibility after saved. The memo must be created by Telegram bot.
The detail of this feature:
1. After you send a message, the bot will reply a text message `success` before. With this feature, the reply message will also include a keyboard. And we add more info such as memo ID, memo visibility into the status text, instead of just a `success`.
2. In the new keyboard, there're some buttons for each visibility option of a memo.
3. You can just click on the button to switch visibility of the memo.
4. If some error occurred, it will notice you on telegram's process banner. You can click again to retry.
5. If everything goes OK, the reply message will update to shows the current status of memo, and the process banner will …
=> feat: set memo visibility in telegram

web/src/components/MemoEditor/index.tsx
=> fix: use `??` in className use

store/memo.go
For memo with equal sorting time (e.g., sorted by creation time, where memos created via an API may occur within the same second), the one with a higher ID should be placed in the front.
=> chore: listMemos sort by id for memos post/update at the same time

web/src/less/setting.less
Since we have split the *Setting* into a page instead of dialog, its height could expand to the whole screen instead of a fixed value.
=> fix: auto expand height of setting page

web/src/components/Header.tsx
The ID of the header archived is the same as the ID of the header settings.
=> fix: header archived id

api/v1/system.go
While making a request to */v1/status*, the *User* cache will be modified unexpectedly. After that, if you request */user/me* again, the response *User* doesn't have *OpenID* and *Email* field.
=> fix: OpenID was disappear sometimes

server/resource.go
Some images generated in Apple devices will get an invalid orientation while generate the thumbnail. This PR just fix it.
=> fix: invalid orientation of image thumbnail in Apple devices

web/src/utils/resource.ts
Some resource's filename contains special characters, such as *+*, so we need to escape the filename before generate a link.
=> fix: escape on resource filename

server/resource.go
Currently, the resource link has two forms like below:
- `/o/r/:resourceId/:publicId`, which is marked as DEPRECATED.
- `/o/r/:resourceId/:publicId/:filename`
Both of them are too redundant. In fact, just a `resourceId` is enough to fetch a resource.
So I made this PR to add support for a new link form like `/o/r/:resourceId`.
For compatible with the old version, the old styles are still be supported, but should migrate the the new one.
And in the next version, I'll change the link in frontend code to this new form.
=> feat: Add support for purged resource link

web/src/components/kit/Dropdown.tsx
#1919 
just change `dark:border-zinc-800` to `dark:border-zinc-700`
Preview:
=> chore: change dropdown's background color in dark mode

docker-compose.dev.yaml
This is just a optimization for developers.
While we have already cached the *GOPATH* of container into the host before.
But the Golang's mod (which contains only source code) could be shared with the common *GOPATH* in the host, instead of a separated directory only this project, this will save a lot of disk spaces.
The binary in *GOPATH* should still cached in our project's path, because the container OS may different with the host.
=> chore: split Go binary and src for dev

api/v1/memo.go
In `/api/v1/memo/all`, the params `visibility` can be set as any values, which will cause anonymous request to fetch memos not `PUBLIC`.
=> fix: visibility param override the user auth state

api/v1/resource.go, server/telegram.go
This PR split the code for resource blob save into a function. After that, all resource upload use this function to save blob, include:
- Upload from HTTP API `POST /resource/blob`
- Upload from HTTP API `POST /resource` with external URL link.
- Upload from Telegram message
=> chore: split save resource asset

web/src/pages/Auth.tsx
- Updated the localization key used for the sign-up failure message in the `handleSignUpButtonClick` function of `Auth.tsx`.
- Replaced `common.signup-failed` with the correct localization key `message.signup-failed` to ensure proper localization.
- This fix ensures that the correct localization key is used for the sign-up failure message, providing accurate translations and a better user experience.
=> fix: incorrect localization key for sign-up failure message

api/v1/tag.go, web/src/labs/marked/parser/Tag.tsx
Currently, if you try to write a tag and add a comma right after it, e.g. `I love using #Memos, it's great`, a tag named `#Memos,` will be created instead of `#Memos`, which is what I expected. This is solved by adding commas to the set of excluded characters in the tag regex in both the front end and back end, and this could be expanded by excluding all punctuation characters using `[[:punct:]]`.
=> fix: exclude commas in tags

web/src/locales/en.json
fix build error: Argument of type '"resource.clear"' is not assignable to parameter of type 'Translations'.
=> fix: add resource.clear to en.json

api/v1/tag.go, api/v1/tag_test.go, web/src/labs/marked/parser/Tag.tsx
The new regex uses the `u` modifier in the frontend regex which is only supported on es6 and above, but I think it's not a huge deal.
Related to #1957
=> fix: exclude all punctuation chars except underscore in tags

api/v1/jwt.go
这里在登录后生成了两个token：access_token、refresh_access；
access_token有效期是24h，refresh_token有效期是7天，理论上只要refresh_token有效，即使access_token过期了也应该重新生成新的access_token，但是目前的实现先判断了access_token的有效，如果无效就直接返回401了，就导致只要超过24h就需要重新登陆。
改为取消对于access_token有效期的判断，只有refresh_token也失效了才返回401；
=> fix: access token will expired after 24h

store/db/db.go
The option "_journal_mode=WAL" is currently *not* being applied when provided in the DSN.
This issue affects only new memos installations, not older ones where the database journal was properly set to WAL mode by the previous sqlite library go-sqlite3.
[modernc.org/sqlite](https://pkg.go.dev/modernc.org/sqlite) DSN parsing is different from [go-sqlite3](https://github.com/mattn/go-sqlite3). It requires the `_pragma=` prefix and even some options order matter.
https://gitlab.com/cznic/sqlite/-/issues/115
By the way, as stated at sqlite documentation, it's a good practice to keep "cache=private" and "foreign_keys=0" explicit, even though it's the current default behavior, as sqlite defaults may change at some point.
Closes #1985
=> fix: database is locked

web/src/locales/ja.json
It is strange to translate "about" as "Notes について". However, if we define "について" as "about", the sentence becomes "について Memos". It is better not to translate here.
=> chore: update ja.json

web/src/pages/ResourcesDashboard.tsx
This commit addresses a display issue with the empty state when the resourceList style is set to Grid. In the Grid style, the empty state was not being displayed correctly, leading to a layout inconsistency.
=> fix: empty state display issue with resourceList style Grid

api/v1/auth.go
api/v1/auth/相关接口未应用convertUserFromStore方法，会导致User对象获得类型存在问题，导致User定义的`json:`相关的字段转化失效。 导致输出json未被正确格式化
The related interfaces in api/v1/auth/ are not utilizing the convertUserFromStore method, which can result in issues with the type of the User object. This can cause the json:-related fields defined in the User struct to be ineffective, leading to incorrect formatting of the output JSON.
*/api/v1/auth/signin* error example:
```
{
"ID": 11,
"RowStatus": "NORMAL",
"CreatedTs": 1690099547,
"UpdatedTs": 1690099547,
"Username": "***",
"Role": "USER",
"Email": "",
"Nickname": "***",
"PasswordHash": "***",
"OpenID": "01901a30-cbc5-403b-a428-***",
"AvatarURL": ""
}
```
=> /api/v1/auth/signup json format 

web/src/components/MemoList.tsx
This commit addresses an issue #2016  with the hashtag filter, which was not working correctly for hashtags containing Unicode characters. The filter was only capturing single-letter hashtags instead of complete hashtags.
=> fix: hashtag filter for Unicode characters

web/src/pages/Archived.tsx, web/src/pages/Explore.tsx
Add a search bar in Archived Memos page
Resolves #607 and #660
=> feat: add search bar in archived and explore pages

web/src/components/MemoContent.tsx
**Background:** Currently if auto-collapse is on, long posts will be fully shown first and then collapsed, leading to significant content flash.
This PR will render all posts with a max height to avoid the content flash, then check `scrollHeight` instead of `clientHeight`.
=> fix: avoid content flash on auto collapse

api/v1/auth.go, api/v1/system.go, api/v1/system_setting.go, web/src/components/DisablePasswordLoginDialog.tsx, web/src/components/Settings/SSOSection.tsx, web/src/components/Settings/SystemSection.tsx, web/src/locales/en.json, web/src/pages/Auth.tsx, web/src/store/module/global.ts, web/src/store/reducer/global.ts, web/src/types/modules/system.d.ts
Currently, password-based login is still activated if one is using SSO login, allowing one to log into the same account using both password and SSO. Also, if one signs up via SSO, then a random (20 character) password will be generated for the new user, which could be used to log into the new account, circumventing SSO, even if it would require brute force because the password is randomized.
This PR aims at solving this possibly unwanted behaviour by adding a server setting to disable password-based login altogether.
In the future it might also make sense to remove the `NOT NULL` constraint on the password field in the user database table as well as adding a way for users to individually decide whether they want to use password-based login, SSO-based login or both. But that is something …
=> feat: add system setting to disable password-based login

cmd/memos.go, store/resource.go
With this PR, we can move resource blob from local file back to database, the only thing you need is run a sub command of *Memos*.
First of all , **STOP Your Container** and **Backup anything**.
Second of all, **STOP Your Container** and **Backup anything**.
AGAIN and AGAIN and AGAIN, **STOP Your Container** and **Backup anything**.
If you have finish all above, just run a cmd:
```
docker run -it -v ~/.memos/:/var/opt/memos ghcr.io/usememos/memos:latest mvrss
```
PS: Next version, we'll add support to move resource between more storages.
=> feat: add command to move blob from local to db

web/src/components/ShareMemoDialog.tsx
Use user avatar in ShareMemoDialog instead of default logo.
=> feat: use user avatar in ShareMemoDialog

web/src/locales/zh-Hans.json
Add some translation content
``` json
"disable-password-login": "禁用密码登录",
"disable-password-login-warning": "所有用户将无法使用密码登录。如果配置的身份提供程序失效，不在数据库中恢复此设置将无法登录。删除身份提供程序时也要格外小心❗",
"disable-password-login-final-warning": "如果你知道自己在做什么，请输入 \"CONFIRM\"",
"enable-password-login": "启用密码登录",
"enable-password-login-warning": "启用所有用户的密码登录。如果希望用户同时使用 SSO 和密码登录，请开启密码登录"
```
=> chore: update zh-Hans.json

plugin/telegram/api_edit_message.go, plugin/telegram/api_get_updates.go, plugin/telegram/api_send_message.go, plugin/telegram/bot.go, plugin/telegram/chat.go, plugin/telegram/message.go, plugin/telegram/update.go, plugin/telegram/user.go, server/telegram.go
This PR fix all `ID` fields's type from `int` to `int64`, to avoid break on 32bit machines.
=> fix: all ID from int to int64 to avoid 32bits machine break

web/package.json, web/pnpm-lock.yaml, web/src/labs/marked/parser/BlockLatex.tsx, web/src/labs/marked/parser/InlineLatex.tsx, web/src/labs/marked/parser/index.ts
Add LaTeX support using react-katex library
This commit integrates the react-katex library to add LaTeX support to the project. It enables the rendering of both inline and block-level LaTeX code.
For inline LaTeX:
- Supports \( and \) delimiters
- Supports $ delimiters
For block-level LaTeX:
- Supports \[ and \] delimiters
- Supports \begin{equation} and \end{equation} delimiters
- Supports $$ delimiters
This feature enhances the readability and expressiveness of mathematical and scientific content.
=> feat: support LaTeX with react-katex

web/src/labs/marked/parser/InlineLatex.tsx
Fix parsing and rendering of multiple inline LaTeX code within a single line.
pre fix:
fixed:
=> fix: multiple inline latex parsing

web/src/pages/DailyReview.tsx
This PR add a small feature, to persist current selected date of DailyReview page. With the feature, while we refresh the DailyReview page, we needn't to select date again.
=> chore: persist selected date of DailyReview page

web/src/components/MemoResourceListView.tsx
This PR just optimize image resources layout while the number of image is 4.
Before this PR, it'll be like this:
```
| IMAGE1 | IMAGE2 | IMAGE3 |
| IMAGE4 |
```
After this PR merged, it'll be like this:
```
| IMAGE1 | IMAGE2 |
| IMAGE3 | IMAGE4 |
```
This layout looks better, and come from *WeChat* *Moments*.
=> chore: optimize layout of image resources

web/vite.config.ts
This PR fix some settings for vite proxy, so we can keep the origin HTTP Host header and add some XFF headers to the backend API server.
=> fix: vite proxy setting

web/src/locales/de.json
TItle, basically. Just a typo fix.
=> chore: fix typo in german localization

cmd/memos.go, cmd/mvrss.go, cmd/setup.go, server/server.go, store/driver.go, store/memo.go, store/memo_organizer.go, store/memo_relation.go, store/resource.go, store/sqlite/memo.go, store/sqlite/memo_organizer.go, store/sqlite/memo_relation.go, store/sqlite/resource.go, store/sqlite/sqlite.go, store/sqlite/tag.go, store/sqlite/user.go, store/sqlite/user_setting.go, store/store.go, store/tag.go, store/user.go, store/user_setting.go, test/server/server.go, test/store/store.go
This is the last PR for #2280 , which move `vacuum` from `Store` to `Driver`, and remove the db instance reference of `Store`.
Close #2280
=> chore: store vacuum and clean

web/src/grpcweb.ts, web/vite.config.ts
While calling api v2 in container or any other dev environment which is not on `localhost`, all the v2 API will failed. This PR just fixed this bug.
=> fix: apiv2 failed in container

cmd/memos.go, docker-compose.dev.yaml, go.mod, go.sum, main.go, server/profile/profile.go, store/mysql/activity.go, store/mysql/idp.go, store/mysql/memo.go, store/mysql/memo_organizer.go, store/mysql/memo_relation.go, store/mysql/migrate.go, store/mysql/migration/dev/LATEST__SCHEMA.sql, store/mysql/migration_history.go, store/mysql/mysql.go, store/mysql/resource.go, store/mysql/seed/10000__reset.sql, store/mysql/seed/10001__user.sql, store/mysql/seed/10002__memo.sql, store/mysql/seed/10003__memo_organizer.sql, store/mysql/seed/10004__tag.sql, store/mysql/storage.go, store/mysql/system_setting.go, store/mysql/tag.go, store/mysql/user.go, store/mysql/user_setting.go
This PR will add support for *MySQL* as storage backend driver.
Close #1816, #2269
=> feat: support mysql as backend storage driver

docker-compose.dev.yaml, web/package.json
This PR just add some useful tools for developers into `docker-compose.dev.yaml`.
With the PR, developers can just run some tools simply with `docker compose`, such as:
To regenerate typescripts bind of gRPC protocol, you can just run:
```
docker compose run --rm buf
```
To lint the golang code before commit or push to the repo, just run:
```
docker compose run --rm golangci-lint
```
To lint the javascript code before commit or push to the repo, just run:
```
docker compose run --rm lint
```
=> feat: add some dev tools in the docker compose

web/src/locales/it.json
Changed translation of "private" to "Privato" instead of "Privao" (missing the letter "t")
=> chore: update it.json translation

.github/workflows/backend-tests.yml, .github/workflows/build-and-push-release-image.yml, .github/workflows/build-and-push-test-image.yml, .github/workflows/frontend-tests.yml, .github/workflows/proto-linter.yml, .github/workflows/uffizzi-build.yml
- Bump `actions/checkout` version from `v3` (uses Node 16 which reached eol) to v4 (Node 20).
- Bump `actions/setup-go` from `v3` to `v4` (this version adds caching support and also other performance improvements).
=> chore: bump actions/checkout; actions/setup-go to v4

docker-compose.dev.yaml
This PR just simplified the docker-compose.dev.yml. There're only two changed:
- use `cosmtrek/air` to replace `golang` as the API's image
- use `pnpm` to replace `npm` as the WEB's image.
=> chore: optmize docker-compose.dev.yml

store/db/mysql/idp.go, store/db/sqlite/idp.go
This PR just fix a small bug ( maybe it's a new feature), that while we create IdentityProvider, the `Id` attributes has no affect.
=> fix: CreateIdentityProvider without id

store/db/mysql/resource.go, store/db/sqlite/resource.go
This PR just fix a small bug ( maybe it's a new feature), that while we create `Resource`, the `Id`, `CreatedTs`,`UpdatedTs`,`MemoID` attributes has no affect.
=> fix: create resource without some attributes

store/db/mysql/memo.go, store/db/sqlite/memo.go
This PR just fix a small bug ( maybe it's a new feature), that while we create `Memo`, the `Id`, `CreatedTs`,`UpdatedTs`,`RowStatus` attributes has no affect.
=> fix: create memo without some attributes

store/db/mysql/user.go, store/db/sqlite/user.go
This PR just fix a small bug ( maybe it's a new feature), that while we create `User`, the `Id`, `CreatedTs`,`UpdatedTs`,`RowStatus` attributes has no affect.
=> fix: create user without some attributes 

store/db/mysql/storage.go, store/db/sqlite/storage.go
This PR just fix a small bug ( maybe it's a new feature), that while we create `Storage`, the `Id` attribute has no affect.
=> fix: create storage without some attributes 

server/server.go
This PR just change the burst rate limit from `60` to `100`.
Currently when we load the index page, there're many web resources ( about 88 uri ) to be load, the original burst limit `60` is too small, and will cause there server return `429` to refuse the browser to load.
PS, the resource number of the index page in my case:
- Document: 1
- CSS: 10
- Images: 1
- Javascript: 49
- XHR/Fetch: 27
Total: 88
=> fix: index page failed with 429

store/db/mysql/tag.go, store/db/sqlite/tag.go
This PR fix a bug on `ListTag`, which not work on omit all params.
For example, if I call it with `&store.FindTag{}`, it will return nothing instead of all the *Tag*s.
=> fix: ListTag not support omit params

cmd/memos.go
This PR just add `profile.Data` in the booting log.
=> chore: print profile.Data in boot log

cmd/memos.go, server/server.go
This PR just add *latency* in the request log, which is helpful while debug the performance of Memos
=> chore: add latency in log

api/v2/memo_service.go
This PR just fix a bug in apiv2, which will cause `Visibility` param of `CreateMemo` has no effect in gRPC call.
=> fix: invalid type convert in apiv2

README.md
New shortcut for memos version 0.15.0 and above on IOS
=> chore: update iOS shortcut link

web/src/pages/DailyReview.tsx
This PR changed the storage of selected date in DailyReview. The old value is `localStorage`, which will keep always even if we closed the browser. The new value is `sessionStorage` which will keep only when the browser is running, and reset while the browser is closed. This will be more satisified.
=> chore: switch storage of selected date in DailyReview

.golangci.yaml
The default timeout of *golangci-lint* is 1 minute, but the benchmark shows it always require 1~2 minutes to do this. So I changed the default timeout config of it.
=> chore: change the timeout value of golangci-lint

README.md
Hello! I have done a few minor changes to the shortcut:
- The description in the README. `A shortcut for iOS` -> `Shortcuts (iOS, iPadOS or macOS)`, more consistent with others.
- Shortcut
- A more specific **error message** (like `Error: No API Endpoint`)
- If failed to save, prompt for copying the memo **text to the clipboard**, so that the user can save it manually (rather than losing it).
- Prompt for confirmation after tags being appended. User can either confirm or **modify the text**. This helps when quick saving quotes from an article using share sheet and want to make comments.
=> chore: update Shortcuts link

web/src/components/Settings/MemberSection.tsx, web/src/layouts/Root.tsx
This PR makes a small optimization, that auto extend setting page's height to the whole screen.
=> chore: extend height of setting page

store/db/mysql/user.go, web/src/pages/Setting.tsx
This PR fix a bug, which will cause user's update on `update_ts` failed when using *MySQL* as storage driver.
=> fix: fail to update user's update_ts

.github/workflows/backend-tests.yml, .github/workflows/codeql.yml
- restrict codeql and backend tests from running on pull requests with unrelated files
- upgrade codeql: current version is generating a deprecation warning in logs
=> chore: update ci

docker-compose.dev.yaml
This PR disable the notice message like below while running `npm` to lint code:
```
npm notice 
npm notice New major version of npm available! 9.8.1 -> 10.2.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.1
npm notice Run npm install -g npm@10.2.1 to update!
npm notice 
```
=> chore: disable NPM update notice while running lint

api/v2/user_service.go
This PR add a new feature, that allow admin to create token for any exists user.
And it also fixed a bug that the *username* doesn't check before create token.
=> fix: validate username before create token

cmd/memos.go
This PR add a switch to disable the metric collector start from `v0.16.1`, which is mentioned on #2433 .
=> chore: add a flag to change metric switch

api/v1/resource.go, server/integration/telegram.go, server/service/backup/backup.go, store/system_setting.go
This PR remove all pointer of `context.Context`.
=> chore: remote context.Context pointer

server/server.go
This PR just remove the gRPC listener. We only use gRPC behind the gRPC-Gateway, which is not require a independent port listener.
=> chore: disable gRPC listener

server/service/backup/backup.go
It's a small PR, which downgrade the log level while user disable the auto backup by set interval to `0`.
=> chore: downgrade log level for auto backup disable

api/v1/memo.go, web/src/components/MemoEditor/index.tsx, web/src/pages/MemoDetail.tsx
- fix(web/memo): filter out public option
- feat(api/memo): sanity check for disabled public memos
Resolves #2462
=> fix: private memos being public

cmd/copydb.go
This PR just fix a bug on `copydb`.
This command should only do db migrate on a exists *Memos* instance, and shouldn't initial a fresh one. That should only be done by run *Memos* directly.
This PR just prevent `copydb` to do that.
=> fix: prevent copydb to create a fresh memos

cmd/copydb.go
The *Memos* instance initial by install will feed some records in `system_setting` table, and the `copydb` cmd will also check and require it empty.
This PR just skip that check.
=> fix: skip system_setting check while copydb

api/v1/auth.go
We have add a feature in #2402 to support persist the authorized status, but it still break on the cookie's expire. This PR just fixed that.
Because of cookie is not support to set as never expire, we set a 100 years duration as a walk around for that.
=> fix: persist jwt expires by cookie

server/server.go, server/service/backup/backup.go
This PR add a new feature to rotate backup files.
Note: this will change the backup filename suffix from `-20060102-150405.bak` to `.bak.NNN`, which is not compatible with the old version.
=> feat: backup file rotate

web/src/components/MemoEditor/index.tsx
This PR just fixed a bug, while the draft of memo is clean, the localStorage should be clear instead of keep a empty string there.
=> fix: clear localStorage while draft is empty

web/src/components/MemoEditor/index.tsx
keep content on save when access token is invalid
fix #2521
=> fix: keep content and query param on save when access token is invalid

web/src/labs/marked/parser/InlineLatex.tsx
看了一下代码在下面这个commit里面给包了一层div , 不确定当时这个commit是为了解决什么问题提交的 ，感觉这里应该是不需要额外包一层div
https://github.com/usememos/memos/commit/20e5597104c4349df61c112899fab42227ad8c19
fix #2523
fix #2468
=> fix:  parse inline latex as a inline element

web/src/components/MemoResourceListView.tsx
For a single media (such as image), there's a max height class ( `max-h-72` ) to limit its height. This cause the image be crop and looks bad. So I think it could be removed.
=> chore: remove the max height limit for single media

go.mod, go.sum, store/db/db.go, store/db/postgres/activity.go, store/db/postgres/common.go, store/db/postgres/idp.go, store/db/postgres/inbox.go, store/db/postgres/memo.go, store/db/postgres/memo_organizer.go, store/db/postgres/memo_relation.go, store/db/postgres/migration/dev/LATEST__SCHEMA.sql, store/db/postgres/migration/prod/LATEST__SCHEMA.sql, store/db/postgres/migration_history.go, store/db/postgres/migrator.go, store/db/postgres/postgres.go, store/db/postgres/resource.go, store/db/postgres/seed/10000__reset.sql, store/db/postgres/seed/10001__user.sql, store/db/postgres/seed/10002__memo.sql, store/db/postgres/seed/10003__memo_organizer.sql, store/db/postgres/seed/10004__tag.sql, store/db/postgres/storage.go, store/db/postgres/system_setting.go, store/db/postgres/tag.go, store/db/postgres/user.go, store/db/postgres/user_setting.go, store/db/postgres/webhook.go, test/store/memo_test.go
Added PostgreSQL support using [Squirrel](github.com/Masterminds/squirrel)) This comes after our talk in [Issue #2517](https://github.com/usememos/memos/issues/2517) .
- All automated tests are green. 
- Did a bunch of manual checks too, and everything looks good.
I'd love to get your thoughts and any feedback you have. 
@boojack 
To answer the questions we raised in the original issue, I think we can say, it is not worth it to provide a general abstraction to support all three different SQL databases. The SQL builders can do only so little (tried different ones), to help us build sql queries. Golang does not have a decent ORM at this point as well. Hence we will move on by changing the implementation of each driver independently when we have a database schema changes.
=> feat: support Postgres

web/src/pages/MemoDetail.tsx, web/src/pages/UserProfile.tsx
I've found an issue with the UserAvatar size display on the details page. 
The `h-20` className didn't take effect due to the lack of `!important`, resulting in the height remaining at `w-8`. 
This discrepancy in width and height is causing an inconsistency in the avatar dimensions.
before:
After I changed `h-20` to `!h-20`, it look great now:
=> fix: detail page user-avatar size have unexpected height

web/src/components/MemoEditor/index.tsx
This PR fix a bug, while the default `visibility` of memo is empty, the memo editor will show an empty option instead of the default `PRIVATE`.
=> fix: visibility of memo editor is empty

web/src/components/Settings/PreferencesSection.tsx
This PR fix a bug, while the default `visibility` of memo is empty, the visibility row in user preference will show an empty option instead of the default `PRIVATE`.
=> fix: visibility of user preference is empty

.github/workflows/backend-tests.yml, .github/workflows/build-and-push-release-image.yml, .github/workflows/build-and-push-test-image.yml, .github/workflows/frontend-tests.yml
- Bump `actions/setup-go` from `v4` to `v5` (Node 20).
- Bump the `actions/setup-node` version to `v4` (Node 20).
- Bump `pnpm` and `docker` actions to the latest versions.
=> chore: bump actions in workflows

cmd/copydb.go
I just upgraded to v0.18.0 and am getting migration failures into a Postgres database. See #2600 for more context. This PR changes the `SELECT COUNT(*) ...` queries to use squirrel, and adds a hack to fix migration to Postgres. Not the prettiest but I have tested and it works for all database types without issue.
Fixes #2600
<details>
<summary>Successful migration log</summary>
```
/usr/local/memos $ /tmp/memos copydb --from 'mysql://memos:***@tcp(memos)/memos'
---
Server profile
data: /var/opt/memos
dsn: postgresql://memos:***@postgresql/memos
addr:
port: 5230
mode: prod
driver: postgres
version: 0.18.0
metric: true
---
Checking activity...
Checking memo_relation...
Checking resource...
Checking tag...
Checking user...
Checking user_setting...
Checking idp...
Checking memo...
Checking …
```
=> fix(copydb): fix migration to Postgres

server/integration/telegram.go
This PR just trim the dir of filename of the attachments send by telegram bot
=> fix: trim the dirname of attachment send by telegram bot

plugin/telegram/attachment.go, server/integration/telegram.go
As stated by https://pkg.go.dev/path, "path" is mainly for URLs, "path.filepath" for file systems
=> chore: fix misuse of package path instead of filepath.path

api/v1/resource.go
Add an addition tag `{uuid}` to the `replacePathTemplate`.
It is a workaround to leak the public links of a resource when using S3-based object storage. Currently, all resource blobs stored in S3 (R2, OSS) are set to be public. It is insecure as the resources for the private memos are also accessible on the Internet. It happens in many situations. For example, the adversary might gauss the private resources' URLs based on the public memos' URLs even using a timestamp. Also, the resource's accessibility will not be modified when the memo's accessibility is changed.
Using an additional {uuid} might reduce this risk.  Actually, it is better to use a signed URL, but it might bring a large range refaction. As a result, using an additional UUID might help with little modification to the current …
=> feat: add {uuid} in path template when using local storage or S3

bin/memos/main.go, store/migrator.go, test/store/migrator_test.go
- handle mixed path styles
- handle Windows paths
- add tests
- run the migration in a separate goroutine, so server startup doesn't take too long on large databases and/or low-end hardware
- log basic post-migration stats like `INFO    store/migrator.go:52    migrated 34219 local resource paths in 42.8559848s`
=> chore: improve resource internal_path migrator

plugin/storage/s3/s3.go
Fix #2630
---
I noticed that aws-go-sdk was upgraded to v1.24.0 again, and saving resources to R2 failed. I tested Cloudflare R2 and it worked fine with the changes.
=> fix: image upload failed with cloudflare R2

web/src/components/ResourceIcon.tsx
This PR change the resource's `img` to be lazy loading, which could decrease the concurrent request to the server, especially in the `Resource` page or other pages with a lot of images.
=> chore: set image loading to lazy

scripts/docker-compose.dev.yaml
This PR resolved a problem, that the `pnpm install` may failed with `ERR_PNPM_LINKING_FAILED` in some case.
This is because *pnpm* is works by create hard link, which is not working well in docker container.
So we use `npm` to replace `pnpm`.
=> fix: pnpm install failed in docker

web/src/components/CreateIdentityProviderDialog.tsx
The scope of "user" in GitHub OAuth includes permissions to update a user's profile.
=> chore: updating the default scopes of GitHub SSO

web/src/components/MemoEditor/index.tsx, web/src/helpers/utils.ts
Inspired by [this suggestion](https://github.com/usememos/memos/issues/2461).  I tried to match the behavior of GitHub's [Markdown editor](https://docs.github.com/en/get-started/accessibility/keyboard-shortcuts).  I decided to use astricks instead of underscores for italics (which GitHub uses), as the Markdown Guide states asterisks are a [better practice](https://www.markdownguide.org/basic-syntax/#italic-best-practices).
* Bold and unbold highlighted text with (Ctrl/Meta + b)
* Italicize and unitalicize highlighted text with (Ctrl/Meta + i)
* Create blank hyperlink (placeholder is `url`) for highlighted text with (Ctrl/Meta + k)
* Create hyperlink for highlighted with valid URL stored in clipboard with  (Ctrl/Meta + v)
**Limitations:**
* Not being able to bold or italicize current word …
=> feat: Markdown Editor Keyboard Shortcuts

web/src/components/kit/DatePicker.tsx
Resolves [this bug](https://github.com/usememos/memos/issues/2765) where the DatePicker would show a badge for the incorrect date.
=> fix: DatePicker Local Date

web/src/components/MemoEditor/handlers.tsx, web/src/components/MemoEditor/index.tsx
I added this with [this PR](https://github.com/usememos/memos/pull/2763/files), but it was removed with [this commit](https://github.com/usememos/memos/commit/5a723f00fa9d9a6a10e5a929c62abfe31ae2a751).
This PR hooks onto the paste event, if text is highlighted, and there is a valid URL in the clipboard, then the editor will use markdown syntax to turn the highlighted text into a hyperlink with the URL in the clipboard.  This matches the behavior of GitHub.  This especially makes it easier to paste URLs on mobile.
=> feat: Add URL paste handler

test/store/activity_test.go, test/store/idp_test.go, test/store/inbox_test.go, test/store/memo_organizer_test.go, test/store/memo_relation_test.go, test/store/memo_test.go, test/store/resource_test.go, test/store/storage_test.go, test/store/system_setting_test.go, test/store/tag_test.go, test/store/user_setting_test.go, test/store/user_test.go, test/store/webhook_test.go
It's just a matter of explicitly closing the database, so that TempDir.removeAll doesn't fail. This doesn't affect other systems.
=> chore: fix store tests on Windows

web/src/App.tsx, web/src/store/module/global.ts, web/src/store/v1/user.ts
Close #2767.
Locale usage sequence: `storage locale` > `user locale` > `server's default locale`. (same for appearance)
=> fix: server overrides user's locale/appearance

web/src/components/Settings/SystemSection.tsx, web/src/locales/en.json
A lot of users were confused about the use of 'Vacuum' button in the settings->system. Therefore I added a tooltip for this.
At the moment the tooltip text is only in English language.
From [issue #2724](https://github.com/usememos/memos/issues/2724)
=> chore: added tooltip for vacuum button

api/v1/memo.go, api/v2/memo_service.go
Add a webhook when the memos are deleted. Currently, the webhooks are only triggered when the memos are created (C) or updated (U). But the webhook for deleting (D) is missing. I think it is better for the webhook to activate for the entire CURD procedures.
I love memos, and use it heavily. However, I need it to send me a notice as a reminder, like issue #858. I realize that this function is in the roadmap, but I cannot wait to have it. As a result, I recently worked on my community tool [memos-reminder](https://github.com/ertuil/memos-reminder) as a temporary solution. It reads memos using the webhook API, and reads some date/time tags in it, and then sends me reminder emails.
However, I find that the current webhook is not completed, as it will not notify my memos-reminder to delete the …
=> feat: add a webhook action for deleted memos

web/src/components/MemoContent/CodeBlock.tsx
This PR allows users to set Markdown code blocks as 'iframe' to embed videos or external music links from services like Apple Music or Spotify.
=> feat: Enable iframe rendering in markdown code block

web/src/locales/zh-Hant.json
+ Updated traditional chinese translation
=> chore: update zh-Hant

api/v1/memo.go, api/v2/memo_service.go
fix #2814
I am not familiar with golang coding, so please make a double check before merge, especially api v1 version.
After this change, changes to the existing public memos would also be banned in api v2. I don't know if it is in line with the original intent of the public memos (I think the target to disable public memos is to prevent users from causually adding/modifying the content displayed on the public pages).
For api v1, enforce normal user to save as private memo if public memos are disabled, just like CreateMemo.
Besides, I wonder whether the api v1 is deprecated and whether it need updating.
=> fix: avoid making memos public when disabled

plugin/storage/s3/s3.go
=> fix: encode filename when using url prefix for resources

api/v2/v2.swagger.yaml, proto/buf.gen.yaml
I was unable to use the plugin opt `openapi_configuration` to supply the additional API configuration file (it simply doesn't find the file), but it's a matter of API users replacing the first 4 lines of `v2.swagger.yaml` with something like this:
```yaml
swagger: "2.0"
host: "demo.usememos.com"
schemes:
- https
- http
securityDefinitions:
Bearer:
type: apiKey
in: header
name: Authorization
description: >-
Enter the Memos token with the `Bearer` prefix, e.g. "Bearer abcde12345"
security:
- Bearer: []
info:
title: Memos API
version: 2.0.0
``` 
This enables interacting with v2 API using Insomnia built-in Swagger-UI or even using the web-hosted [Swagger Editor](https://editor.swagger.io).
By the way, there's not much control of file name, the plugin will always append ".swagger.yaml".
It's …
=> feat: add buf plugin to generate openapiv2 spec

web/src/components/ActivityCalendar.tsx, web/src/helpers/datetime.ts, web/src/pages/Timeline.tsx
Close #2817
---
For example, if user in the New York timezone, then `new Date('2024-01').getFullYear()` returns 2023, we should treat it as UTC time or local time with an offset.
=> fix: month grouping error in timeline page

web/src/pages/SignIn.tsx
This PR fix a bug, that'll cause the error notification toast not shown while signin failed.
=> fix: signin error notification is not shown

web/src/pages/Archived.tsx
Details written in the commit message.
=> fix: displaying archived memos

scripts/docker-compose.dev.yaml
- add support to start Memos with all database variants
- fix pnpm issues
- remove npm
- move air and golangci-lint images to golang:1.22-alpine with cached binary installation. These tool's images are still at go 1.21 and won't work after latest go.mod upgrade to go 1.22. Also, the reuse of the same image as the back-end will speed-up transfers and lower disk space usage.
- add goimports and go one-off tasks
- add Adminer with auto login for quick database inspections
- use yaml anchors to reuse most of the settings and make maintaining easier
- add introductory comments to ease new developers onboarding
Tested on Linux and Windows hosts.
Supersedes #2909
=> chore: improve docker-compose.dev

web/src/components/MemoActionMenu.tsx, web/src/components/ShareMemoDialog.tsx, web/src/pages/MemoDetail.tsx
I am not familiar with ts/react coding, so please make a double check before merge.
In ShareMemoDialog, user can change the visibility of the memo, so that the memo can be set to public to be viewed by anyone with the link.
related issue: #2868
related pr: #2931
=> feat: add visibility select in ShareMemoDialog

scripts/docker-compose.dev.yaml, web/package.json, web/pnpm-lock.yaml, web/src/App.tsx, web/src/components/MemoContent/CodeBlock.tsx, web/src/components/MemoContent/MermaidBlock.tsx
[MermaidJS](https://mermaid.live/edit#pako:eNqFkUFLAzEQhf_KkFMLBe-LCEWvRbF6kb2MyWQ37WYSJ9mClP5308a6tR7MKe99j0cys1c6GFKN8o6Nx9gygISQZ7NvYz4_WgDPlAhF91UBPDKQtaSz2zGldPsuN3fIBixhHoXSRW455uAxOw1aCnWBzxDgNU3Reu5PmR1BJt2z-xivA-ssmKkrdXFAZsfdb76UbvTEGcrr4x9q7FWdNf8ZVb2EMPyAJ2I4_jZiJDmbKxKPzlS57MNmqjG2T2GStt8kd6nNJm0HtVC-VpR97I-0VbknT61qytWgbFvV8qHksIx0_claNVlGWqgxmjKTB4edoD-bZFwOsqr7Pa15oSLyWwglYnFIdPgCF8SXkQ) is a user-friendly diagramming tool. It is known for making diagram creation easier and faster than writing detailed descriptions. By adding MermaidJS to Memos, I aim to enable users to include various types of diagrams, like mind maps, in their notes. This integration is intended to make the sharing of complex ideas more straightforward and visually appealing, helping to communicate …
=> feat: add mermaid support in codeblock

api/v1/auth.go
As mentioned, this made it impossible to log in via apiv1, simply fixed it.
=> fix: Incorrectly checking whether registration is allowed in the login v1 api

web/src/layouts/HomeLayout.tsx
**Problem:**
For browsers not support <a href="https://caniuse.com/mdn-api_viewtransition">[ViewTransition API | Can I use... Support tables for HTML5, CSS3, etc](https://caniuse.com/mdn-api_viewtransition)</a>, majorly Firefox and Safari, `useNavigateTo`(useNavigateTo.ts) calls `useNavigate` immediately, and it works in most cases except in HomeLayout.tsx.
An error shows `You should call navigate() in a React.useEffect(), not when your component is first rendered.`
**Cause:**
Regressed by this PR: <a href="https://github.com/usememos/memos/commit/dfe29ec766290aec8dbb1769c09dccf2881f0ef4">[chore: tweak route layout · usememos/memos@dfe29ec](https://github.com/usememos/memos/commit/dfe29ec766290aec8dbb1769c09dccf2881f0ef4)</a>
**Fix:**
Follow the correct pattern to call `useNavigate` …
=> fix: firefox/safari to redirect to /explore in HomeLayout

server/integration/telegram.go
If a memos added through telegram is deleted and we try to change the visibility in telegram, server will dereference a nil pointer in the handler when dispatching webhook.
=> fix: telegram callback query handler dereferencing nil pointer if memo not found

web/src/components/MemoEditor/Editor/TagSuggestions.tsx
Hello, I am really enjoying this app so far! This is my first self hosted app and first PR :)
This PR fixes three issues:
| Before | After |
|--------|--------|
| <img width="300" alt="Screenshot 2024-02-26 at 17 34 10" src="https://github.com/usememos/memos/assets/56483075/68b28850-63a2-4c66-ba94-569d07d44bbd"> | <img width="300" alt="Screenshot 2024-02-26 at 17 35 30" src="https://github.com/usememos/memos/assets/56483075/48fa3554-82a9-40c7-8b64-8cf1215e2353"> |
Fix scenario like the following:
```
1. Text #tag text
^ backspace here
2. Text#tag text
^ space
3. Text #tag text
^ tag suggestion opens
```
=> fix: dark mode tag selection and suggestion

scripts/build.ps1
=> chore: fix typo in build script's if statement

web/src/components/MemoEditor/index.tsx
Fix https://github.com/usememos/memos/issues/3026
=> fix: ignore "Tab" key down event when is composing in editor(#3026)

web/src/css/global.css
This PR adds a color-scheme property so that the browser applies the appropriate user agent styles, such as scrollbar color
Learn more about this property: https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme
Also, I've decided to make an experimental change to the scrollbar color in the dark mode, so it will use the corrent dark shades
Here's an example of improvement in scrollbar style for dark themes on Windows in MS Edge:
| Before | After |
|--------|--------|
| ![image](https://github.com/usememos/memos/assets/18244287/ffe6685a-da56-4e3a-b95c-de4203a8d8b2) | ![image](https://github.com/usememos/memos/assets/18244287/1204013a-8383-486f-b294-31bb3ded21da) |
=> feat: improve theming

web/src/components/Settings/SectionMenuItem.tsx, web/src/pages/Setting.tsx
This PR refactors the Settings page menu.
- Added select-none to things that should not be selectable, such as buttons and sections titles. 
- Taken advantage of React hooks for caching to improve performance on page re-renders.
- Minimized code dublication to make future changes easier.
=> chore: settings page improvements

web/src/components/Dialog/BaseDialog.tsx
fix #3049 
I reviewed the performance of the rc-image component during preview and found that the preview of this component is based on @rc-component/portal. I referred to the solution provided by that component.
https://github.com/react-component/portal/blob/815dc89dd74c4799b3604aefa73b94b05914ffb3/src/useScrollLocker.tsx#L23
=> fix: body overflow styles

go.mod, go.sum, plugin/http-getter/image.go
Solving issue https://github.com/usememos/memos/issues/3093
I have removed the sanitization code currently being used for images.
Current logic uses an external html sanitization library i.e. bluemonday, however since we are passing the binary image content and not html/markdown, the process damages the image bytes leading to a malformed image. This library filters out data that are not the standard html tags, which would obviously work against raw image bytes. 
I think sanitizing binary image data is unnecessary in that sense.
=> removed sanitization logic

web/src/components/MemoContent/EmbeddedContent/EmbeddedMemo.tsx
=> fix: link embedded content to uid instead of name

web/src/components/MemoActionMenu.tsx, web/src/locales/en.json, web/src/locales/vi.json
Currently, when going to the link of an archived memo, the action still shows Archive instead of Restore
=> feat: handle restore memo when is in archived memo detail page

server/route/api/v1/tag.go, server/route/api/v2/user_service.go
In the current go 1.21 version used in the project, slices are no longer an experimental feature and have entered the standard library
=> cmd: use the built-in slices library

web/src/components/Navigation.tsx
There is a problem with spanish, portuguese and other languages where even when the words are truncated the icons are shrinking.
=> Set navigation icons to not shrink

internal/util/util.go, server/route/rss/rss.go
We can use the built-in `min` function since Go 1.21.
Reference: https://go.dev/ref/spec#Min_and_max
=> chore: replace util.Min helper with built-in min

server/router/api/v1/tag_service.go, web/src/components/HomeSidebar/TagsSection.tsx
Fix #3309 
What to know:
- Delete tag with or without children should be working after this fix, but the tag is still present in the memo
- the tag deletion still not working if the tag that wants to be deleted is a parent tag (need to discuss how is the expected behaviour if we delete the parent tag)
ex: tag is `#parent/sub1`. The tag is not deleted if the user hovers on #parent and deletes it. But if the user deletes #parent/sub1, it's working as expected. `#parent/sub1` will be deleted with `#parent` still exists.
https://github.com/usememos/memos/assets/67781184/e11432d3-2fba-480a-9e0c-e2c470c0a342
=> fix(tag_deletion): fix deleting tag from tag lists

web/src/components/MemoEditor/Editor/index.tsx
Setting max height to 50vh than limiting to 256px only for better editing in larger screens.
=> Fix: Set max height to 50vh for better viewing for larger screens.

store/db/mysql/resource.go, store/db/postgres/resource.go, store/db/sqlite/resource.go, web/package.json, web/pnpm-lock.yaml, web/src/components/MemoEditor/ResourceListView.tsx, web/src/components/MemoEditor/SortableItem.tsx
Related to #3297
Implements drag and drop functionality for updating resource orders in the editor using the `dnd-kit` library.
- Integrates `dnd-kit` in `ResourceListView.tsx` to enable drag and drop functionality, allowing users to rearrange resources intuitively.
- Adds a new component `SortableItem.tsx` to handle individual draggable items within the resource list.
- Utilizes `arrayMove` from `@dnd-kit/sortable` to update the resource list's state upon successful drag and drop, ensuring the new order is reflected in the UI.
- Employs `useSensors` from `@dnd-kit/core` with `MouseSensor` and `TouchSensor` to support drag operations across different devices.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/usememos/memos/issues/3297?share …
=> feat: implement drag and drop for resource order in editor

server/router/api/v1/v1.go, server/server.go
Restore the behavior broken by 5d967f41d968c882c342e65578a36da2e2df9579
=> chore: respect supplied listening address

store/db/mysql/migration/prod/0.22/01__memo_tags.sql, store/db/mysql/migration/prod/0.22/02__memo_payload.sql
This pull request addresses #3348, which implements the fix I worked out, mentioned in the issue.
SQLite migrations and PostgreSQL migrations seems to be fine, as they are not trying `DROP`ping non-exist columns.
Besides, a version bump (e.g. 0.22.0 -> 0.22.1) is suggested to aware the downstream users to upgrade.
=> Fix MySQL database migration 0.21.0 -> 0.22.0

go.mod, go.sum, server/server.go
A panic would lead to a server shutdown now.
This PR is trying to make the server more robust, by adding panic recover interceptor for echo server and grpc server.
=> feat: add panic recovery middleware for grpc and echo server

web/src/locales/fr.json, web/src/locales/ja.json, web/src/locales/mr.json, web/src/locales/pt-BR.json, web/src/locales/ru.json, web/src/locales/tr.json
Updated by "Cleanup translation files" hook in Weblate.
Translate-URL: https://hosted.weblate.org/projects/memos-i18n/english/
=> chore: update translation files

server/router/api/v1/memo_service.go
When using the dedicated feature in Memos' user settings to export all memos to Markdown files inside a ZIP folder, the output doesn't feature any kind of distinction for memos by their set visibility. While this is not a big issue for personal backups, it can reveal itself problematic if exporting the data to share it with other people, or maybe deploy to a static site generator, because there is nothing in the files that distinguishes public memos from private or workspace-restricted ones.
This pull request simply modifies the ExportMemos server function, to add the Visibility status to the end of every exported file name inside the ZIP, right after the date (which is left intact). For example, the file for a public memo would now be called: `YYYY-MM-DDThh:mm:ss+hh:mm-PUBLIC.md`.
An …
=> feat: write memo visibility in file names when exporting

.gitignore, server/router/api/v1/resource_service.go
Sometimes there may be some resource store on file system disappeared, as the user here described https://github.com/RyoJerryYu/obsidian-memos-sync/issues/14 .  (Though I don't know how this happened)
Returning a gRPC NotFound error would be better than returning Internal error. Then we could got a 404 status code when we use gRPC-web or gRPC-gateway API if this was happened.
=> feat: return not found error instead internal error for local file not exist

server/router/api/v1/v1.go
Add CORS allow all for gRPC-gateway handler. Trying to fix #3573 .
=> fix: allow cors for grpc gateway handler

server/server.go
Because of https://github.com/soheilhy/cmux/issues/99, PATCH requests can't be handled by Memos v1 API (0.22+). Thankfully, cmux has a parameter to add supported HTTP methods for `cmux.HTTP1Fast`.
With some user agents and reverse proxy servers, this issue can't be reproduced because the PATCH request reused previous HTTP connections which were used by GET or POST requests, and didn't go through the match process of cmux.
This patch (pun intended) also fixes #3494, https://github.com/mudkipme/MoeMemosAndroid/issues/187 and https://github.com/mudkipme/MoeMemos/issues/189.
=> fix: PATCH requests on /api/v1 not working

server/router/api/v1/memo_service.go
When using the "export to Markdown" feature in Memos, the files included in the ZIP folder don't feature any kind of reference to their alphanumeric UID from the server's database, which completely breaks the point of links inside the files made with the `[[memos/<uid>]]` format, since it's impossible to know which Markdown file this kind of string inside other files refers to.
This pull request modifies the ExportMemos server function, to add the UID of every memo immediately after the date in the filename. For example, an exported memo would now be called: `YYYY-MM-DDThh:mm:ss+hh:mm-AbcDefGhiJklMnoPqrStu1-PUBLIC.md`.
Technically a follow-up of #3538, and could very well have been included there, but I unfortunately only thought about this now, after having started using the linking …
=> feat: write memo UID in file names when exporting to Markdown

web/src/components/MemoContent/CodeBlock.tsx
A code block of unknown language (that is, a language not treated as special by Memos and not handled by highlight.js) should fall back on rendering its plaintext content. However, the content is never properly escaped before it is appended to the DOM, and thus any string that happens to contain HTML is unsafely rendered. This commit fixes the issue by ensuring that, when none of the previous cases handle the text, any HTML entities are escaped first.
=> fix: code blocks of unknown languages cause HTML injection

.github/workflows/build-and-push-release-image.yml
Fixes #3645, currently the release containers are build from the release branches, which are created in preparation for a release. This causes some users with automated CI/CD to either deploy a pre-release version or be notified of a release version before it has actually been released. 
This change switches the workflow to be triggered by tags, which are created on the release version.
=> chore: build release containers from tags rather than branches

README.md
The previous page no longer exists.  The new one takes users to the Docker directions for Windows.
=> fix: dead link in README.md

store/db/mysql/memo.go
In version v0.22.4, filtering timeline via tags when using MySQL as database driver will cause the `ListMemos` API to fail due to an invalid query. 
This pull request removes the `%` in the query and should resolve the issue.
=> fix: tag query for mysql

web/src/pages/SignIn.tsx, web/src/pages/SignUp.tsx
See #3747 for more context on the ask behind this pull request.
- Altered both `web/src/pages/SignIn.tsx` and `web/src/pages/SignUp.tsx` to explicitly disable the `spellcheck` and `autocapitalize ` fields. This should improve the mobile experience of typing in your username/password 
- Altered both `web/src/pages/SignIn.tsx` and `web/src/pages/SignUp.tsx` to have explicit `autocomplete` fields. This will make it easier for password managers to autofill these fields. Typically they fallback to the input id or name, but explicit autocomplete values won't hurt 😄 
Maintainers, If you see any issues with this PR, please let me know and I can make some changes. 
Thanks in advance.
=> fix: explicitly disabling `autocapitalize` and `spellcheck`

Dockerfile
Container image size reduced from 63.8MB to 42.5MB.
- Change base image to distroless (static-debian12)
- Remove unnecessary RUN instructions
- Add build options
- add options to delete debug information
- add options to remobe embedded paths
- https://github.com/GoogleContainerTools/distroless
=> perf: reduce image size by 21.3MB

server/router/api/v1/resource_service.go
Images in the web client have a maximum width of 700px.
This PR is to update the width of thumbnails being generated to align with the home/explore page image max width. This will allow the images to take up the full space provided
Images with a width smaller than the thumbnail width are not scaled up. Note: for these images the cache and resource will be the same image.
See PR comment for original discussion: https://github.com/usememos/memos/pull/3821#discussion_r1731674073
e.g. 
original 512px width compared to new 700px width
smaller than 700px width does not get upscaled
=> chore: set max thumbnail width to home/explore image max width

scripts/compose.yaml
- change `docker-compose.yaml` to `compose.yaml`
- remove deprecated field
Close #3855
=> chore: migrate of Docker compose v2

test/store/memo_test.go
Added test for searching memos by tags, which has been fixed in #3785.
=> test: add test for searching memos by tags

server/router/api/v1/auth_service.go
When the user fails to login using username and password on `/api/v1/auth/signin`, the error message should be `unmatched username and password`, instead of `unmatched email and password`
=> chore: replace `unmatchedEmailAndPasswordError` with unmatchedUsernameAndPasswordError`

web/src/components/ActivityCalendar.tsx
Use translated day of week values for calendar as per issue (https://github.com/usememos/memos/issues/3879)
Design decisions:
Used the existing translations but some of these are 3 char translations vs the 2 char strings that are currently used in the calendar. e.g. English was `Mo` for Monday but after translating the value is `Mon`. From testing this looks to not be an issue for most languages. I did notice Hindi has no spaces, but need to evaluate if this can be fixed with a translation update or if CSS needs to be used for just a select view languages
English
Spanish
German
Hindi
=> chore: use translations for calendar days

web/src/components/ActivityCalendar.tsx
Settings the start day of the week to Monday causes the memo calendar to display incorrectly
Memos
System calendar
This seems to only be an issue for months where the first day is on a Sunday
Calendar after update, the start day now matches up even when the first day of the month is a Sunday e.g. Sep 2024 and Dec 2024:
Sep 2024
Memos
System calendar
Oct 2024
Memos
System calendar
Nov 2024
Memos
System calendar
Dec 2024
Memos
System calendar
=> fix: update first day logic for months starting on Sunday

web/src/components/MemoContent/CodeBlock.tsx
By default, DOMPurify removes the content of iframe, but I think iframe is a commonly used tag
=> fix: iframe rendering

store/db/postgres/memo.go
This is a fix for the bug https://github.com/usememos/memos/issues/3892
Case insensitive search was not working for postgres driver, to mitigate this I changes `LIKE`  to `ILIKE`
=> fix: case insensetive memo search for postgres

proto/buf.gen.yaml
Hi there - I was trying to build this locally, and with docker, and kept receiving errors during `pnpm build`:
```
src/types/proto/store/workspace_setting.ts:8:44 - error TS2307: Cannot find module '@bufbuild/protobuf/wire' or its corresponding type declarations.
```
While digging through everything - it looks like the plugins used by `buf` aren't tracked by any package managers/lockfiles/etc, it seems like `buf` pulls them in dynamically.
Looking at https://buf.build/community/stephenh-ts-proto?version=v2.2.0 - it looks like v2.2.0 came out September 19th and I suspect it generates code that's incompatible with something, because when I changed the buf.gen.yaml file to reference a specific version (the previous one listed) - everything compiles without issue.
I'm guessing there's some …
=> buf: specify version of stephenh-ts-proto plugin

Dockerfile
Reverts usememos/memos#3849, and close https://github.com/usememos/memos/issues/3931
=> chore: revert "perf: reduce image size by 21.3MB"

web/src/components/PreviewImageDialog.tsx
Allow mobile user to zoom by temporary set the `user-scalable` attribute to `yes` in `viewport meta`. 
Reset to `no` before the dialog destroy.
=> feat: allow mobile user zooming in image preview

web/src/components/MemoContent/EmbeddedContent/EmbeddedMemo.tsx, web/src/components/MemoView.tsx, web/src/pages/Archived.tsx
As per the below Discord comment, 
memos with a date set in the future have their relative time display as `now`
e.g. of future date (1 day in the future) showing `now`
After code change date references the future
=> fix: show future relative dates

web/src/components/UserStatisticsView.tsx
Adds a couple of arrows to more easily navigate through months. Only shows on hover, like the dot menu next to them
=> feat: add month toggle on hover

web/src/components/HomeSidebar/TagsSection.tsx, web/src/components/TagTree.tsx
As per issue https://github.com/usememos/memos/issues/3947#issuecomment-2381853439 the tag list does not show usage numbers in tree view. This PR aims to add usage numbers
Design decisions:
Parent nodes only has a number next to them if they are uniquely used, they do not contain the sum of their child nodes
Examples:
Notes from the above:
- Parent1 has no direct reference so no usage number is displayed
- Parent2 has a direct reference so a usage number is displayed
- Parent3 child1 has no direct reference so no usage number is displayed
- Parent2 child1 has a direct reference so a usage number is displayed
=> feat: add tag count to tree view

web/src/App.tsx
As per issue https://github.com/usememos/memos/issues/4005 when toggling the operating system them between light and dark mode the web UI only takes effect after page reload
This PR allows for the them to change as the operating system theme changes without refreshing the page
e.g. 
Dark
Light
This change work with Browser theme settings as well
=> fix: apply system theme dynamically

web/src/pages/Home.tsx
As per issue: https://github.com/usememos/memos/issues/2765#issuecomment-2431346655
Memos are stored with a UTC timestamp. When the calendar dates are selected the UTC offset is not used to create the timestamps between which the memo creation date should fall.
e.g. of incorrect memos being shown
This PR aims to include the UTC offset in filter dates
e.g. of correct memos being shown
=> fix: use UTC date for calendar filter

web/src/components/MemoEditor/Editor/index.tsx
This PR fixes the issue where new list items do not inherit the indentation level of the previous item. Now, when pressing the Enter key in a list, the new line will have the same indentation as the previous line.
=> fix: automatic indentation follows previous lines in lists (#4048)

store/db/mysql/memo.go, web/src/components/PreviewImageDialog.tsx
Issue: https://github.com/usememos/memos/issues/4024
This PR is to allow for navigating between images using the `left` and `right` keyboard keys when viewed in the image dialog.
Build decisions:
- Because the dialog does not have an input the event listener had to be added to `document` for the keys to fire the events.
- Due to the listener being on `document` it is outside of the component scope so the state does not get updated on key pressed. According to [this](https://stackoverflow.com/a/53846698) article there are a couple of ways around it. I chose event listener re-registration so that I did not need to keep 2 sets of state in sync (one foe keyboard, one for mouse) and existing functionality could be used.
=> feat: navigate image view with keyboard keys

web/package.json, web/pnpm-lock.yaml, web/src/components/PagedMemoList/PagedMemoList.tsx
https://github.com/usememos/memos/issues/1789
Although above issue is fixed, tap to reload still a bit hard to find and non-intuitive, I feel adding pull to refresh feature will make user experience better. 
Looks like this^
GIF:
=> feat: add pull to refresh for PagedMemoList

server/router/rss/rss.go
Hi folks, the long and duplicate titles in Memos RSS feeds have been a nuissance in an otherwise superlative app for me, so I figured I'd roll my sleeves up and help out 😊 What do you think?
---
This PR removes the content of the `<title>` element in the RSS feeds that Memo produces.
**Why remove?** Every RSS client I can find shows the `<title>` next to the `<description>` when viewing an item. This creates a duplicate (but often trimmed, so less useful) version of `<description>` right above the actual text the user wants to read (often in a much larger font). It similarly makes lists of items in some clients extremely tall, as 128 characters is a lot of hard-to-read text — especially when Memos renders links as their URL in titles.
**Why an empty tag?** The RSS 1.0 and 2.0 specs …
=> feat: remove RSS titles

server/router/rss/rss.go
This change adds the permalink as GUID to RSS feed items. [micro.blog](https://micro.blog) requires feed items to provide a GUID for content ingestion.
**Please note**: I was not able to verify this change locally as the `u/USER/rss.xml` 404s before and after this change locally.
=> Add id to RSS feed items

store/migration/mysql/0.25/00__s3_reference_length.sql, store/migration/mysql/LATEST.sql
This PR  fixes #4322.
I have verified this on my own Memos instance, running MySQL 8.4, by running: 
```
ALTER TABLE `resource` MODIFY `reference` TEXT NOT NULL DEFAULT ('');
```
After this change, B2-backed file uploads appear to work as expected.
Caveat: I am not familiar with how this project likes to handle version numbering and DB migrations, so please accept my apologies if this migration isn't in quite the right place at this time.
=> Allow storing resource references >256 chars long in mysql

server/router/api/v1/webhook_service.go
This removes spaces that can cause invalid URLs. While I was using the webhooks I kept pasting urls with spaces and discovering the problem in the logs later.
Eg,
`http://192.168.1.10:8080/webhook ` is accepted, but will return 404 when used. This change removes the space at the end
=> feat: Trim space on webhook url

plugin/httpgetter/html_meta.go
#4413 It doesn’t seem like a complete solution; it would be better if page preview could be done from the frontend.
=> fix: Prevent previewing internal network web pages.

plugin/httpgetter/html_meta.go, plugin/httpgetter/html_meta_test.go
The previous fix for issue #4413  (commit #4421) still has some flaws. An attacker could potentially exploit a crafted redirection address to redirect to the internal network, thereby leveraging the GetLinkMetadata API to probe internal network information.
=> Prevent attackers from exploiting redirect attack GetLinkMetadata API

web/src/components/MemoEditor/Editor/index.tsx
Closes: https://github.com/usememos/memos/issues/4396
It looks like the indentation match was overwritten instead of being appended to the sub list symbol.
I fixed this so the matched spacing is properly appended to the symbol when enter is pressed when editing a sublist.
I also discovered an issue where if the parent node was a list, the child nodes would be indented properly, but the symbol was not included after pressing enter. I fixed this by recursively digging into the child nodes.
Kudos to the easy dev environment setup. I was able to start debugging the issue in <5 minutes 😄
=> Match sublist indentation when adding a new item

web/src/components/MemoDisplaySettingMenu.tsx, web/src/locales/en.json, web/src/locales/zh-Hans.json
=> update i18n zh-hans

web/src/components/MemoEditor/ActionButton/UploadResourceButton.tsx
Displays a loading spinner while files are being uploaded to provide visual feedback to user
Change:
- Displays the `LoaderIcon` component when `uploadingFlag` is `true`
Benefits:
- Clearly indicates to user that file upload is in progress
- Prevents the appearance of the app freezing after selecting a large file
https://github.com/user-attachments/assets/36fa05eb-025d-44cc-84dd-522f6c3ff5ee
=> Add loading spinner during file upload process

server/router/api/v1/health_service.go, server/router/api/v1/v1.go
This pull request introduces a health check service to the API v1 server. The main changes include adding a new health service implementation, registering the health server, and updating imports to support the new functionality.
Key changes:
* Added a new health check service implementation in `server/router/api/v1/health_service.go`, which includes a `Check` method to verify the service status.
* Updated `server/router/api/v1/v1.go` to import the necessary gRPC health check package.
* Updated the `APIV1Service` struct in `server/router/api/v1/v1.go` to embed `grpc_health_v1.UnimplementedHealthServer`.
* Registered the health server in the `NewAPIV1Service` function within `server/router/api/v1/v1.go`.
closes #4498
=> Implement grpc health service checking database connection

web/src/store/v2/user.ts
- set partial only the relevant user stats instead of only adding up stats
closes #4500
=> fix: user stats changes based on selected tab

web/src/locales/en.json
Noticed this typo from the screenshot in the new 0.24.1 release.
=> Fix typo s/contnet/content/.

store/db/postgres/memo_filter.go
closes #4510 
and the if statement was unnecessary as the condition is already checked.
=> fix: use valid query parameters for postgres

web/src/components/PreviewImageDialog.tsx
- escape key closes the modal
- zooming is a bit smoother
closes #4501
=> fix: prevent double effect on image modal wheel event

web/src/store/v2/user.ts
This PR adds functionality to detect and set the locale based on the browser's language settings (`navigator.language`) when the user is not logged in.
Let me know if anything else needs to be updated. Thanks!
Closes #4557
=> feat: set locale based on browser language when user is not logged in

web/src/components/MemoEditor/ActionButton/UploadResourceButton.tsx, web/src/components/MemoEditor/index.tsx
Improve drag/drop file upload experience with better visual feedback and state management. This enhances clarity and usability.
**Changes:**
- Allow file drop on entire area of `MemoEditor`
- Add clear drag/drop visual feedback with dashed border, cursor: copy, and loading spinner
- Pass `isUploadingResource` from `MemoEditor` to `UploadResourceButton` as a prop to always display spinner during active uploads
- Add `isDraggingFile` state in `MemoEditor` to track drag UI state
https://github.com/user-attachments/assets/76b7d85a-2ba7-45e9-b5bf-7da941470ee9
=> Improve visual feedback in MemoEditor for drag/drop file uploads 

web/src/components/MemoView.tsx
My fix supports what is described in the issue, if tags like "#something/nsfw" or "#blabla-nsfw-blabla" are also supposed to be supported, a quick change can be made from this `tag.startsWith("nsfw")` to this `tag.includes("nsfw")`.
=> Fixes #4604: Support Child Tags in NSFW Blur Feature

bin/memos/main.go, server/profile/profile.go, server/router/api/v1/v1.go, server/server.go
Fixes #4649. I've decided to add a separate flag that overrides the `--addr` and `--port` flags for the CLI.
=> feat: Support listening on a UNIX socket

web/src/locales/en.json
Remove duplicated word "Enable" and add a space
Follow-up to cd5abd9 and [this discussion](https://github.com/orgs/usememos/discussions/4627)
=> fix: remove duplicated “Enable” in settings label

web/src/pages/SignIn.tsx
This makes the UI cleaner, instead only showing the "Sign in with ..." buttons.
=> Hide "or" when password auth disabled

web/src/components/MemoEditor/Editor/index.tsx
https://github.com/user-attachments/assets/c029120f-956e-4384-9b0e-5e97e45dfb5a
I am not always able to reproduce it. But this often happens on iOS Safari on my iPhone 13 Pro and iPad Pro M2. 
From what I can tell, it seems there is a race condition between the default behaviour of the event handler and the `insertText` to be inserted. It only seems to happen with the task list continuation, maybe because it is slightly longer than the other list continuations.
This fix removes the race condition and inserts the newline manually before the `insertText`. 
After implementing this fix, I don't see this occurring on my devices anymore.
Thanks for considering the fix.
=> fix(editor): Prevent race condition and ensure correct list continuation on Enter

web/src/components/MemoEditor/index.tsx, web/src/pages/MemoDetail.tsx
Uses the parent memo visibility as default when creating comments. I find that kinda useful but feel free to close this one if it does not fit your idea of that default visibility 🙂 
https://github.com/user-attachments/assets/a6458786-f266-41ca-ad2e-933cace008bc
✌️
=> fix: Inherits memo visibility for default comment visibility

web/src/components/DateTimeInput.tsx
According to dayjs documentation
the `dayjs(inputValue, DATE_TIME_FORMAT, true)` construct does not work without `CustomParseFormat` plugin, [link](https://day.js.org/docs/en/parse/string-format),
so the code contains an error.
Also, according to the documentation, dayjs develloper recommended to use ISO 8601 [link](https://day.js.org/docs/en/parse/string)
is international and better readable for the default format.
It's a continuation of the bug #4746 
Using ISO 8601 without `T` is acceptable in JS. 
I suggest to make it the main one for `DATE_TIME_FORMAT`
It preserves readability when editing the date of records and uses the classic international "big-endian" date format.
It would be ideal to put the preferred date format in the settings, but this requires more resources.
=> fix: dayjs - ISO 8601 compatible DATE_TIME_FORMAT

server/router/api/v1/user_service.go
**Problem**
Users were experiencing 404 errors when uploading or viewing avatar images in their profile. The issue occurred because the backend was generating incorrect avatar URLs that pointed to a non-existent endpoint.
Root Cause
The convertUserFromStore function in server/router/api/v1/user_service.go was generating avatar URLs using the pattern /file/{userName}/avatar, but the actual API endpoint defined in the proto specification is /api/v1/{name=users/*}/avatar.
Solution
Changed avatar URL generation from /file/{userName}/avatar to /api/v1/{userName}/avatar
Updated the logic in convertUserFromStore function to use the correct API endpoint path
Added comprehensive tests to verify the fix works for all avatar URL scenarios
**Technical Details**
File modified: …
=> fix: correct avatar URL generation to resolve 404 errors

server/runner/memopayload/runner.go
The reason is that the `HasCode` property is now set by the presence of `Code` or `CodeBlock` elements in the note, but the `Code` block is mostly (almost always) used to highlight important words in the text (e.g. variables) that are not code, but such notes are mistakenly caught in the `HasCode` filter. The new behaviour marks notes with the `HasCode` flag only if they contain a `CodeBlock`.
I think this behaviour of the system is more correct.
PS: Due to the fact that the `HasCode` property is only updated when the note is saved, the new logic will only be applied when modifying old/creating new notes.
=> set HasCode only for CodeBlock

web/src/components/MemoView.tsx
If a note is pinned, it will be highlighted with a slightly brighter background colour.
This allows you to quickly visually separate pinned notes from regular notes.
samples:
=> feat: highlight pinned memos

README.md
Fixes #4847
This adds hyperlinks to the prerequisites in the README file on GitHub, as discussed in #4847.
Let me know what you think!
=> Hyperlinks in README Prerequisites

README.md
Adds hyperlink for Docker in "Quick Start Prerequisites," as discussed in #4880.
closes #4880
=> Added Docker hyperlink in README

web/src/components/MemoContent/CodeBlock.tsx
=> fix(syntax-highlighting): Adds missing CSS imports to CodeBlock.tsx

server/router/api/v1/activity_service.go, web/src/components/Inbox/MemoCommentMessage.tsx, web/src/locales/de.json, web/src/locales/en.json, web/src/store/user.ts
| Before    | After |
| -------- | ------- |
| <img width="1994" height="664" alt="image" src="https://github.com/user-attachments/assets/94c29d4a-096c-4b35-9d6d-09af84d06e3b" /> | <img width="1990" height="660" alt="image" src="https://github.com/user-attachments/assets/33ce1a66-1893-4feb-ad5d-db4721c90789" /> |
If a comment on a memo has been deleted, it produced an infinite loading item in the authors inbox. This PR will fix this and also adds the possibility to delete inbox items (failed and archived ones).
=> feat(inbox): handles errors while fetching and adds possibility to delete items

web/src/components/MemoActionMenu.tsx
This relates to my question [here](https://github.com/usememos/memos/issues/4928). Basically I was wondering if memos could support an alternate host for the "Copy Link" button. I noticed a mention of the environment variable `MEMOS_INSTANCE_URL` and as far as I can tell it isn't really used for anything.. So in this PR I have used it for this purpose.
I don't usually work with typescript or go so please forgive me if I am making some egregious error (though this is a pretty simple change).
~I could see an argument that the behavior should be maintained to copy `window.location.origin` in the case that `MEMOS_INSTANCE_URL` is unset so I think I'll see if I can make that work, but as far as I can tell from my quick testing this does exactly what I want as is.~ --------------did this
Now.. …
=> Use MEMOS_INSTANCE_URL for "Copy Link"

plugin/filter/common_converter.go, plugin/filter/dialect.go, store/db/mysql/memo_filter_test.go, store/db/postgres/memo_filter_test.go
The tag filter was broken for MySql and Postgres Drivers since 0.25.0. 
MySql error:
```
2025/08/01 08:50:38 ERROR server error method=/memos.api.v1.MemoService/ListMemos error="rpc error: code = Internal desc = failed to list memos: Error 3141 (22032): Invalid JSON text in argument 1 to function json_contains: \"Invalid value.\" at position 0."
```
Postges error:
```
2025/08/01 09:07:47 ERROR server error method=/memos.api.v1.MemoService/ListMemos error="rpc error: code = Internal desc = failed to list memos: pq: could not determine data type of parameter $2"
```
Problem was for MySql was that the tag needs to be a valid json string which can be achieved by adding quotes. For Postgres it was required to also add the `::json` type to the query.
Closes #4937
=> fix(tags): ensure JSON array elements are properly formatted in SQL queries

plugin/filter/dialect.go, store/db/postgres/memo_filter_test.go
Seeing an error on main when trying to select a date filter when using postgres db (16.1):
```
Uncaught (in promise) ClientError: /memos.api.v1.MemoService/ListMemos INTERNAL: failed to list memos: pq: function pg_catalog.extract(unknown, bigint) does not exist
```
and the DB error:
```
2025-07-31 20:04:19.154 UTC [133] ERROR:  function pg_catalog.extract(unknown, bigint) does not exist at character 465
2025-07-31 20:04:19.154 UTC [133] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2025-07-31 20:04:19.154 UTC [133] STATEMENT:  SELECT memo.id AS id, memo.uid AS uid, memo.creator_id AS creator_id, memo.created_ts AS created_ts, memo.updated_ts AS updated_ts, memo.row_status AS row_status, memo.visibility AS visibility, memo.pinned …
```
=> fix calendar filter?

server/router/api/v1/memo_service_converter.go, store/db/mysql/memo.go, store/db/postgres/memo.go, store/db/sqlite/memo.go, store/memo.go
This PR partially addresses #4946 by removing an extra call to the database done per memo just to retrieve the parent memo's name. The ParentID field has been removed as it was only used to later get the parent memo's name so replacing it with a ParentUID field makes more sense.
Because refactoring the ListMemos and the database drivers is a large and risky change it's best to approach this in multiple stages and this change seems like an quick win.
I have tested the changes with sqlite, mysql 8, and postgres 17.
=> #4946 - remove call to db for parent memo name

server/router/api/v1/v1.go
Fix gRPC Gateway connection issue on macOS when server address is empty
When starting memos without specifying the --addr parameter (default configuration),
all /api/v1/* endpoints fail on macOS with the following error:
```
{"code":14, "message":"connection error: desc = \"transport: Error while dialing:
reading server HTTP response: unexpected EOF\"", "details":[]}
```
The /healthz endpoint works correctly, indicating the HTTP server is running, but the
gRPC Gateway cannot communicate with the gRPC server.
Cross-Platform gRPC Connection Behavior Difference:
When `Profile.Addr` is empty (default case), the gRPC Gateway attempts to connect using
the `:port` format. Our testing reveals platform-specific behavior:
Linux (✅ Works):
:8083 → ✅ Successfully connected
:8083 → ✅ Health check …
=> fix: resolve gRPC Gateway connection issue when server address is empty

web/src/components/MemoEditor/ActionButton/AddMemoRelationPopover.tsx, web/src/components/MemoEditor/ActionButton/LocationSelector.tsx, web/src/components/MemoEditor/ActionButton/MarkdownMenu.tsx, web/src/components/MemoEditor/ActionButton/TagSelector.tsx, web/src/components/MemoEditor/ActionButton/UploadAttachmentButton.tsx, web/src/components/MemoEditor/ActionButton/VisibilitySelector.tsx, web/src/locales/en.json
closes #4883 
Add descriptive tooltips to Action Buttons inside Memo Editor.
Thanks @antcoop096 and @mishtigala19 for working on this!
=> feat: Add tooltips to Memo Editor Action Buttons

plugin/filter/common_converter.go, plugin/filter/dialect.go, plugin/filter/filter.go, server/router/api/v1/memo_service.go, server/router/api/v1/memo_service_converter.go, store/db/mysql/reaction.go, store/db/mysql/reaction_filter_test.go, store/db/postgres/reaction.go, store/db/postgres/reaction_filter_test.go, store/db/sqlite/reaction.go, store/db/sqlite/reaction_filter_test.go, store/reaction.go
Another PR to incrementally address #4946.
Implemented filter logic for `reaction` entities inline with `memo` and `user` filters.
The reactions table is now queryable using a filter. ListMemos queries the reactions table using a collection of memo names, reducing all calls to this table to just a single call. If there are 10 memos in the collection, 1 call is made to the database to retrieve the reactions, instead of 10.
`convertMemoFromStore` has fallback logic to query the DB if no reactions are passed in. The goal is to align `convertMemoFromStore` with a method that purely maps DB entities to response entities.
The `ListMemoReactions` public endpoint remains untouched. It is not publicly exposed by the router but it can be in the future.
Tested with sqlite, mysql, postgres.
=> feat: filter/method for reactions by content_id

web/src/store/user.ts
`initialUserStore` has temporal coupling which led to `fetchUserSettings` unintentionally being called before a user was set in the store.
Fixed by moving the call to occur after the user has been set to the store.
Added comments on the order, a todo to try avoid similar bugs, and a console.error call to help debug if it occurs before/if a refactor is done.
fixes: #4978
=> fix: preference not being saved

web/src/components/MemoAttachment.tsx, web/src/utils/attachment.ts
Prevents MIDI files from displaying audio player controls since browsers can't play them natively - MIDI files now appear as downloadable/clickable attachments while other audio formats remain playable.
Fixes issue #4963
=> fix: Midi files show up as playable

server/router/api/v1/memo_service.go
Preventing the SQL syntax error and returning an empty reactions array when no memos are found.
Closes #4983
=> Adds a check to only query reactions when there are actual memos

server/router/api/v1/user_service.go, server/router/api/v1/user_service_test.go
The current implementation of `UpdateUserSetting` in the user service replaces the entire `value` column if the record already exists in the table. The front end sends an update request as soon as a single preference is changed resulting in the backend only receiving a single preference at a time. This means the record is always overwritten with only a single preference.
Also, `UpdateUserSetting` is only used to update the general settings even though method is setup to handle other user settings types. I have added comments explaining how these other types are updated and where we should add logic if we later want to use `UpdateUserSetting` to handle other user setting types.
Also worth considering doing a migration on the `user_setting` table to change the type of the `value` column …
=> fix: preferences being overwritten

web/src/components/ui/sheet.tsx
- Prevent the search bar from automatically focusing when the sidebar is opened and on mobile devices.
- Fix interaction issues on the settings page on mobile devices https://github.com/usememos/memos/issues/4896.
Reference: https://github.com/radix-ui/primitives/issues/1241
=> fix: prevent default focus behavior on open and close events in sheet

web/src/pages/SignIn.tsx
This fix is intended to fix some authorization flow errors that I have encountered with my identity provider. It seems to be standard to encode the `redirect_uri` so that the server can properly parse the request parameters. Without encoding, my server (running pocket-id) is unable to handle the request.
Please let me know if you have any thoughts or suggestions.
=> fix: Update SSO login flow to encode redirect_uri

README.md
the old link of installation guide was 404: 
[https://www.usememos.com/docs/install](https://www.usememos.com/docs/install)
the new one should be:
[https://www.usememos.com/docs/installation](https://www.usememos.com/docs/installation)
=> fix: update the link of Installation Guide

web/src/components/MemoView.tsx
closes #5045
Currently there is no proper way of adding a reaction to a note on mobile because the reaction selector is only shown on hover (`hover` and `focus` are applied altogether when you tap on mobile devices but it's much more of a hack than a real thought user experience).
This PR makes it always visible.
Considering the very small size of the button, I think it's perfectly safe to keep it as visible as it doesn't obscure or shadows any important content.
=> fix: avoid hiding reaction selector and keep it always shown for mobile
